### ISSUE TITLE
ZBS 0.95 Crash when autocomplete

### ISSUE THREAD

**Issue by 1linux** [pkulchenko/ZeroBraneStudio#409] opened 2015-02-08 17:44 UTC
Lua: Error while running chunk
src/editor/autocomplete.lua:598: bad argument #1 to 'insert' (table expected, got nil)
stack traceback:
	[C]: in function 'insert'
	src/editor/autocomplete.lua:598: in function 'CreateAutoCompList'
	src/editor/editor.lua:248: in function 'EditorAutoComplete'
	src/editor/editor.lua:1150: in function <src/editor/editor.lua:1147>
	[C]: at 0x01051beb
	src/main.lua:681: in main chunk
	[C]: at 0x00001c80

**Comment by 1linux** [comment] 2015-02-08 17:46
Please change Line src/editor/autocomplete.lua:598:
From
      `if context[var] then table.insert(apilist, var) end`
To
      `if context[var] and apilist then table.insert(apilist, var) end`

No idea why "apilist" is uninitialized...

**Comment by pkulchenko** [comment] 2015-02-08 17:54
@1linux, what's the sequence of events that lead to this?

> No idea why "apilist" is uninitialized...

I agree, `apilist` should not be `nil`; the only lines I see as suspect are these:

```lua
  if cache[childs] then
    return cache[childs][fragment]
  end
```

**Comment by pkulchenko** [comment] 2015-02-08 18:02
Helmut, your proposed change would fix the issues, but I want to find out what's causing it and fix there... Thank you for the report!

**Comment by 1linux** [comment] 2015-02-08 19:29
Paul,
the sequence was: 
I had these lines of code:

    local GPIO = require('periphery').GPIO
    
    -- Open GPIO 10 with input direction
    local gpio_in = GPIO(2, "in")
    -- Open GPIO 12 with output direction
    --local gpio_out = GPIO(12, "out")
    while true do
    	local value = gpio_in:read()
    end
    gpio_in:close()
    gpio_out:close()

The I tried to insert this line:
	'print(value)'

When typing the "a", ZBS crashed.

**Comment by 1linux** [comment] 2015-02-08 19:48
And of course youre right, the source of problems has to be found...
There is another line that causes problems.
Seems to happen randomly, but always when I type the second character of some word.

Lua: Error while running chunk
src/editor/autocomplete.lua:592: bad argument #1 to 'insert' (table expected, got nil)
stack traceback:
	[C]: in function 'insert'
	src/editor/autocomplete.lua:592: in function 'CreateAutoCompList'
	src/editor/editor.lua:248: in function 'EditorAutoComplete'
	src/editor/editor.lua:1150: in function <src/editor/editor.lua:1147>
	[C]: at 0x01051beb
	src/main.lua:681: in main chunk
	[C]: at 0x00001c80

**Comment by pkulchenko** [comment] 2015-02-08 20:30
Helmut, where do you insert the `print(value)` line? I tried both at the end and inside the loop, but I'm not getting the error. What do you have in your `user.lua` file? Do you have any non-standard API files? Thanks.

**Comment by pkulchenko** [comment] 2015-02-08 20:31
I think the second error is cause by the same issue: `apilist` being `nil`. It just hits a different branch there...

**Comment by pkulchenko** [comment] 2015-02-08 21:39
Helmut, I managed to reproduce the issue; it seems to be happening only with `acandtip.strategy = 1`. Checking what may be going on...

**Comment by pkulchenko** [comment] 2015-02-09 00:07
@1linux, this issue should be fixed, but if you are using `acandtip.strategy` set to 1 or 0 (please confirm), I suspect there may be other issues, which I'm checking on.

**Closed** 2015-02-09 00:06 UTC
Labels: Bug

**Comment by pkulchenko** [comment] 2015-02-12 02:22
@1linux, did the last change work for you? Did you indeed set `acandtip.strategy` to 1 or 0?

**Comment by 1linux** [comment] 2015-02-22 22:21
Sorry for the late answer :-(
Afaik I never changed `acandtip`, so it should have been the default value.
No problem anymore, with neither value 0, 1 or 2.

**Comment by pkulchenko** [comment] 2015-02-22 22:32
No problem; thank you for the update. It's a bit strange as I'd expect that branch to be only hit when `acandtip.startegy` is not 2. I'm glad the issue is fixed and will include it in the next release.
