### ISSUE TITLE
[BUG] Comments with mark down cannot be copied/cut

### ISSUE THREAD

**Issue by andrewstarks** [pkulchenko/ZeroBraneStudio#412] opened 2015-02-11 17:01 UTC
On Windows with (01ef664895 2015/11/02)

```lua
-- You can cut and paste this comment.
-- You `cannot` cut and paste this comment.
-- You _cannot_ cut and paste this comment.
```

**Comment by pkulchenko** [comment] 2015-02-11 17:22
Andrew, that's a feature, not a bug. These comments have "invisible" markup when rendered and Scintilla doesn't allow that markup to be deleted. You can still copy or cut (without deletion) and then delete with `Del` or `Backspace`.

This is a duplicate of #40 and #267. See [markup documentation](http://studio.zerobrane.com/doc-markdown-formatting) and #326 for details. I'll mention this "feature" on the `markdown-formatting` page.

**Closed by pkulchenko** 2015-02-11 17:22 UTC

**Comment by andrewstarks** [comment] 2015-02-11 22:34
copying does not work, however. That is a bug, i would think.

Also, if Scintilla (which is what is underneath ZBS?) does not provide a way to make it work as expected, then it's probably not worth discussion. However, this is not "least surprising behavior". IMHO: It should copy/cut/paste the naked text, as is, regardless of the on-screen presentation.

My .02 anyway.

**Comment by pkulchenko** [comment] 2015-02-11 23:37
Yes, copying does work (both Ctrl-C and Shift-Ins); the cutting doesn't work for the reason stated above. I can try to detect if the deletion has failed (if I can) and repeat it manually, but it's a bit cumbersome and there is no one point where it happens (as Ctrl-X and Shift-Del are handled differently). I'll check...

**Comment by S0lll0s** [comment] 2015-03-31 22:56
seconding that Ctrl-X should remove the text regardless. This makes refractoring Markdown'd code a PITA and I just started using it (markdown *does* make for pretty documentation)
