### ISSUE TITLE
Add option for not terminating debugger on document close

### ISSUE THREAD

**Issue by madmaxoft** [pkulchenko/ZeroBraneStudio#461] opened 2015-05-16 13:56 UTC
Currently ZBS terminates the debugger when the document containing the "current line" marker is closed. This behavior doesn't fit too well with my interpreter - the interpreter loads all the files in the folder and operates on those, so closing any single one of those shouldn't terminate the interpreter.

**Comment by madmaxoft** [comment] 2015-05-16 14:26
To be more specific: This relates to pkulchenko/ZeroBranePackage#15. The package needs to open a specific file in order for BreakIntoDebugger to work; if that file gets closed, the debugger is terminated, which is something unexpected.

**Comment by pkulchenko** [comment] 2015-05-16 15:40
But this should apply to the file with the current line marker. Why would the user be closing file with the current line marker? I'm wary of adding one more config option to handle this case...

**Comment by madmaxoft** [comment] 2015-05-16 15:56
In this particular case, the file being opened is an automatically generated one that the user has actually no idea that it is in there in the first place, it is only created to allow debugging (and BreakIntoDebugger support) for this particular interpreter.

If you can think of a nicer solution to all this, I'd be glad to change the workflow, I just report what I've fallen victim of several times already :) I wanted to close the file while the interpreter was running, so that no more breakpoints get reported back to ZBS, but just as I closed it, the debugger would break there, causing the entire interpreter to terminate, despite me checking that the current line marker is not there.

**Comment by pkulchenko** [comment] 2015-05-16 17:39
I don't see why the page would be closed; there is a check in `ClosePage`, which is only applied when there is a current marker in a file:

```lua
    -- check if the debugger is running and is using the current window;
    -- abort the debugger if the current marker is in the window being closed
    if debugger and debugger.server and
      (editor:MarkerNext(0, CURRENT_LINE_MARKER_VALUE) >= 0) then
      debugger.terminate()
    end
```

In fact, if there are breakpoints in a tab that is closed, they are not reset, even though I remember having code that does this; I'm checking on this.

So, in your case is there or is there not a current line marker in the tab you are closing? If it is, then it's closed by design, but if not, we need to check what happens in that case...

**Comment by madmaxoft** [comment] 2015-05-16 20:20
Resetting breakpoints is not needed, since ZBS ignores breaks in code that is not in an open editor.

In my case the current line marker appears in the file (the interpreter hits the breakpoint) just before I click Close, so instead of closing the window I accidentally terminate the interpreter.

**Comment by pkulchenko** [comment] 2015-05-16 20:35
> Resetting breakpoints is not needed, since ZBS ignores breaks in code that is not in an open editor.

Right; I checked the code and if breakpoint is hit in a file that is not opened, it will issue "out" command to get out of that file.

> In my case the current line marker appears in the file (the interpreter hits the breakpoint) just before I click Close, so instead of closing the window I accidentally terminate the interpreter.

Then the solution is easy: don't click when the current line is in the file ;). Technically speaking, nothing is dependent on the page being opened; this is mostly to avoid the confusion of debugging being paused in some unknown location.

What I can do is move `onEditorClose` callback to be called before current line marker check, which will allow you to write a callback handler to remove current line marker, which will keep the debugging running as the result. I just need to look at what the dependency on the order may be, but you can let me know if this is going to work for your case.

**Comment by madmaxoft** [comment] 2015-05-16 21:10
The location isn't really unknown, you can always get back to it using the Stack window.

I think your solution will work alright for me. I'll just have to decide whether to continue debugging in such a case, or just hide the marker but keep ZBS in the "breakpoint hit" state.

**Closed** 2015-05-28 21:19 UTC

**Comment by pkulchenko** [comment] 2015-05-28 21:22
@madmaxoft, I think I found a better solution. I added `onEditorPreClose` callback, which is called before the debugging is stopped and the page is closed. You can check for the current marker and either remove it to allow debugging to continue or even reject closing the tab if you want (you need to return `false` from the callback).

I'm also thinking that it may make sense to have a dialog that says "The debugging is stopped in this tab. Would you like to terminate the debugging?" and if the user answers "No", then the debugging is not terminated. Would it make sense or would it be too much?

**Comment by madmaxoft** [comment] 2015-05-29 06:10
That might actually be a very good idea to be built into ZBS itself. It's highly unlikely that someone was closing a tab to stop debugging, it's more likely a mistake, so a question is in order. Perhaps with a config option to set a default answer, in case someone was actually using it.

**Comment by pkulchenko** [comment] 2015-05-29 06:15
I'm not sure about (yet another) config option, but `"Debugging has been suspended in the file you are attempting to close. Do you want to stop debugging in addition to closing the file?" [Yes] (close and stop), [No] (close and not stop), [Cancel] (don't close)` should probably work.
