### ISSUE TITLE
Changing the height of the bottom panel does not show the ghost line on Linux

### ISSUE THREAD

**Issue by CapsAdmin** [pkulchenko/ZeroBraneStudio#638] opened 2016-05-01 09:29 UTC
Resizing the width of the file tree shows the ghost line correctly but not the bottom panel. 

This works as expected on windows 10 in a vm.

**Comment by pkulchenko** [comment] 2016-05-01 16:45
Is it the same in the upgrade branch? There is probably not much I can do as it's handled by wxwidgets.

**Comment by CapsAdmin** [comment] 2016-05-01 17:28
Yes it's the same

**Comment by pkulchenko** [comment] 2016-05-01 20:09
Ok. Can you provide a screenshot? Unfortunately, this is likely related to wxAUI changes in wxwidgets, that are mostly on hold due to development in the "dynamic AUI" branch, which has been going on for a while, so there is a small chance that this will get fixed. Closing as "component limitation".

**Closed by pkulchenko** 2016-05-01 20:09 UTC
Labels: Component limitation

**Comment by CapsAdmin** [comment] 2016-05-01 23:01
I'm not sure what to screenshot. While you resize the file tree panel you see a vertical ghost handle instead of a live update. But the horizontal ghost handle doesn't show on the bottom panel.

It's really minor, I just thought I'd point it out.

**Comment by pkulchenko** [comment] 2016-05-01 23:14
You mean the ghost line that follows the mouse cursor when you move it up/down, right? I'll see if I can reproduce it on the aui sample that comes with wxwidgets, but at this point there is not much I can do...

**Comment by CapsAdmin** [comment] 2016-05-02 07:28
Further testing reveals that it actually shows when the editor is maximized but not otherwise.
