### ISSUE TITLE
how to use build-win32.sh

### ISSUE THREAD

**Issue by sonoro1234** [pkulchenko/ZeroBraneStudio#598] opened 2016-02-13 10:44 UTC
Hi Paul,

I have with old MSYS but svn is not found. MSYS2 makes me use gcc 5.1
which is the alternative for using any gcc version wanted

Best
victor bombi

**Comment by sonoro1234** [comment] 2016-02-13 12:33
with MSYS2 I get this:
```
checking build system type... ./config.guess: unable to guess system type

This script, last modified 2010-09-24, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEA       D
and
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

If the version you run (./config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2010-09-24

uname -m = i686
uname -r = 2.4.1(0.294/5/3)
uname -s = MSYS_NT-6.0
uname -v = 2016-02-03 11:08

/usr/bin/uname -p = unknown
/bin/uname -X     =

hostinfo               =
/bin/universe          =
/usr/bin/arch -k       =
/bin/arch              = i686
/usr/bin/oslevel       =
/usr/convex/getsysinfo =

UNAME_MACHINE = i686
UNAME_RELEASE = 2.4.1(0.294/5/3)
UNAME_SYSTEM  = MSYS_NT-6.0
UNAME_VERSION = 2016-02-03 11:08
configure: error: cannot guess build type; you must specify one
mingw32-make: *** No targets specified and no makefile found.  Stop.
Error: failed to build wxWidgets

```

**Comment by sonoro1234** [comment] 2016-02-13 12:45
In wxlua site instructions are to build from wxWidgets\build\msw\

**Comment by sonoro1234** [comment] 2016-02-13 15:45
./configure --build=x86-winnt-mingw32
as found in https://wiki.wxwidgets.org/Compiling_wxWidgets_with_MSYS-MinGW solves the issue

**Comment by sonoro1234** [comment] 2016-02-13 15:51
but then:
```
Configured wxWidgets 3.1.0 for `x86-winnt-mingw32'

  Which GUI toolkit should wxWidgets use?                 msw
  Should wxWidgets be compiled into single library?       no
  Should wxWidgets be linked as a shared library?         no
  Should wxWidgets support Unicode?                       yes (using wchar_t)
  What level of wxWidgets compatibility should be enabled?
                                       wxWidgets 2.8      yes
                                       wxWidgets 3.0      yes
  Which libraries should wxWidgets use?
                                       STL                no
                                       jpeg               builtin
                                       png                builtin
                                       regex              builtin
                                       tiff               no
                                       zlib               builtin
                                       expat              no
                                       libmspack          no
                                       sdl                no

-j1
/c/LUA/ZBbuild/build/wxWidgets/bk-deps gcc -c -o wxregex_regcomp.o -DNDEBUG -D__WXMSW__   -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0 -I/c/LUA/ZBbuild/build/wxWidgets/lib/wx/include/msw-unicode-static-3.1 -I./include -mthreads -Wall -Wundef -mthreads -Os -fno-keep-inline-dllexport  ./src/regex/regcomp.c
/c/LUA/ZBbuild/build/wxWidgets/bk-deps gcc -c -o wxregex_regexec.o -DNDEBUG -D__WXMSW__   -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0 -I/c/LUA/ZBbuild/build/wxWidgets/lib/wx/include/msw-unicode-static-3.1 -I./include -mthreads -Wall -Wundef -mthreads -Os -fno-keep-inline-dllexport  ./src/regex/regexec.c
/c/LUA/ZBbuild/build/wxWidgets/bk-deps gcc -c -o wxregex_regerror.o -DNDEBUG -D__WXMSW__   -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0 -I/c/LUA/ZBbuild/build/wxWidgets/lib/wx/include/msw-unicode-static-3.1 -I./include -mthreads -Wall -Wundef -mthreads -Os -fno-keep-inline-dllexport  ./src/regex/regerror.c
/c/LUA/ZBbuild/build/wxWidgets/bk-deps gcc -c -o wxregex_regfree.o -DNDEBUG -D__WXMSW__   -D_FILE_OFFSET_BITS=64 -DwxDEBUG_LEVEL=0 -I/c/LUA/ZBbuild/build/wxWidgets/lib/wx/include/msw-unicode-static-3.1 -I./include -mthreads -Wall -Wundef -mthreads -Os -fno-keep-inline-dllexport  ./src/regex/regfree.c
rm -f /c/LUA/ZBbuild/build/wxWidgets/lib/libwxregexu-3.1.a
ar rc /c/LUA/ZBbuild/build/wxWidgets/lib/libwxregexu-3.1.a wxregex_regcomp.o wxregex_regexec.o wxregex_regerror.o wxregex_regfree.o
ar: /c/LUA/ZBbuild/build/wxWidgets/lib/libwxregexu-3.1.a: No such file or directory
Makefile:13916: recipe for target '/c/LUA/ZBbuild/build/wxWidgets/lib/libwxregexu-3.1.a' failed
mingw32-make: *** [/c/LUA/ZBbuild/build/wxWidgets/lib/libwxregexu-3.1.a] Error 1
Error: failed to build wxWidgets

```

**Comment by pkulchenko** [comment] 2016-02-13 17:56
Victor, I'm not sure what the issue is as I'm building on Windows also using a combination of msys2 (although an older version) and mingw-tdm without issues.

I pushed several changes that switch wxlua repository from svn to git (as I forked the original repository to introduce my changes for wxwidgets 3.1 upgrade), so you may try using your old build setup. I don't plan to try the most recent msys2 as my current setup works for me, but if you still have the issue on upgraded master, I'll try to take a look.

**Comment by pkulchenko** [comment] 2016-02-19 21:55
> ar rc /c/LUA/ZBbuild/build/wxWidgets/lib/libwxregexu-3.1.a wxregex_regcomp.o wxregex_regexec.o wxregex_regerror.o wxregex_regfree.o
> ar: /c/LUA/ZBbuild/build/wxWidgets/lib/libwxregexu-3.1.a: No such file or directory

Victor, the error is a bit strange as it's supposed to build that file it's complaining about. I didn't find much relevant information online on this issue.

I'm closing this; reopen if this still not working for you on the current master. If you found a way to fix this, update the ticket as it may help the others. Thanks.

**Closed by pkulchenko** 2016-02-19 21:55 UTC
