### ISSUE TITLE
error in analyse

### ISSUE THREAD

**Issue by qgenesist** [pkulchenko/ZeroBraneStudio#1117] opened 2021-06-08 16:30 UTC
W 10 64 bit  ZB 1.90 (9 Feb 2020) 

function matDTAREF(eptr)
  local REF   = ''
  local riptr = fhNewItemPtr()
  local piptr = fhNewItemPtr()

  riptr:MoveToRecordItem(eptr)
  local RLBL = fhGetTag(riptr)
  piptr:MoveToParentItem(eptr)
  local PLBL = fhGetTag(piptr)

  local LBL = fhGetTag(eptr)

  if RLBL ~= PLBL
  and PLBL ~= '' then
    -- ie: INDI.BIRT.DAT
    REF = string.format('%s.%s.%s', RLBL, PLBL, LBL)
    break
  elseif RLBL == PLBL then

    -- ie: INDI.INDI.NAME
    REF = string.format('%s.%s', RLBL, LBL)
    break
  elseif PLBL == '' then
    -- ie: INDI..INDI
    REF = string.format('%s', RLBL)
  end

--  local rc, ilvl, sGCTAG, imin, imax, imaxsiz, imaxCONT, imaxCONC = fhGetGedcomInfo(eptr)
  if not DTAREF[REF] then
    local vr =  fhIsValidDataRef(REF)
    local pi =  fhHasParentItem(eptr)
    local ci =  fhHasChildItem(eptr)
    local ps =  fhHasPrevSibItem(eptr)
    local ns =  fhHasNextSibItem(eptr)
    local hf =  fhIsHidden(eptr)
    local uf =  fhIsUDF(eptr)
    DTAREF[REF] = {REF = REF, vr = vr, pi = pi, ci = ci, ps = ps, ns = ns, hf = hf, uf = uf}
  end
  return
end

I put this in its own untitled scratch to verify--

using analyze I get:
![Untitled](https://user-images.githubusercontent.com/32033615/121223250-f2b5c300-c84c-11eb-9921-9c8a963a7189.png)

**Comment by pkulchenko** [comment] 2021-06-08 17:02
@qgenesist, this appears to be a duplicate of #1095 and fixed in 97b1ae125, so you may want to use a newer version.

**Closed by pkulchenko** 2021-06-08 17:02 UTC
