### ISSUE TITLE
Compile Lua 5.3 code

### ISSUE THREAD

**Issue by raingloom** [pkulchenko/ZeroBraneStudio#501] opened 2015-07-17 12:28 UTC
With project interpreter set to Lua 5.3, compiling `print ( 2 // 3 )` gives an error, but it can still be ran.
I only use the compiler for syntax checking, so I'm not worried, but others may run into problems.

**Comment by pkulchenko** [comment] 2015-07-17 17:24
This is a duplicate of #493, so you may follow the discussion there.

**Closed by pkulchenko** 2015-07-17 17:24 UTC
