### ISSUE TITLE
onFiletreePreExpand event failed

### ISSUE THREAD

**Issue by fireymerlin** [pkulchenko/ZeroBraneStudio#697] opened 2016-09-17 15:37 UTC
Just upgarded to ZBS 1.40
When I start ZBS, the Output pane has the following message in it:
onFiletreePreExpand event failed: src/editor/filetree.lua:920: attempt to perform arithmetic on field 'wxFSW_EVENT_CREATE' (a nil value)

**Comment by pkulchenko** [comment] 2016-09-17 15:54
@fireymerlin, this is a duplicate of #693. Either install into a new folder or delete `bin/wx.dll` file (as it's a leftover from the previous version).

**Closed by pkulchenko** 2016-09-17 15:54 UTC
