### ISSUE TITLE
Minor (?) issue related to "code completion" (or "tooltip"?)

### ISSUE THREAD

**Issue by livingingote** [pkulchenko/ZeroBraneStudio#985] opened 2019-04-15 09:12 UTC
Hi! If I type ``print(`` then click on the code completion/explaination popup (?), ZeroBraneStudio crashes and I receive the message "ZeroBraneStudio quit unexpectedly" etc.

I'm on OSX Yosemite 10.5.5 and have replicated this bug with both the latest release and the v.1.80 release downloaded from the ZeroBrane homepage.

I am a complete beginner in programming - looking to learn Lua 5.1 - so I've tried to explain the bug as clearly as possible... Please ask me if I can help any further.
Edit: Just to be clear, I'm not asking for programming advice and haven't encountered any other bugs with ZeroBrane yet. Thanks.
Here is a screenshot:

![Screen Shot 2019-04-15 at 09 44 57](https://user-images.githubusercontent.com/49637261/56120278-b684c180-5f65-11e9-9f1c-4aeeb353b261.png)

**Comment by livingingote** [comment] 2019-04-15 17:11
Like last time, with a `(` , if I click on the resulting tooltip then ZeroBrane will crash again. I hope this helps...
![Screen Shot 2019-04-15 at 18 04 03](https://user-images.githubusercontent.com/49637261/56151366-fcaf4480-5fa8-11e9-91d8-d25798f4e224.png)

**Comment by pkulchenko** [comment] 2019-04-15 23:24
@livingingote, thank you for the report. Yes, it's an issue with wxwidgets code, which I already submitted a patch for, but the IDE core has not yet been updated to use the latest version of wxwidgets (as there are some other issues in wxlua that need to be resolved first). It's a duplicate of #712, so I'm closing this one. Until the upgrade the solution is "don't do it" ;(.

**Closed by pkulchenko** 2019-04-15 23:24 UTC
