### ISSUE TITLE
When pressing cmd-P to switch files, cmd-f (find) doesn't search on the right file

### ISSUE THREAD

**Issue by WhiteNoise** [pkulchenko/ZeroBraneStudio#577] opened 2016-01-03 14:07 UTC
First, thanks for the great lua IDE! When I'm working I rely heavily on on Command-P and search to find things. Currently when you use command P to switch files, and then try to use search immediately after, it will search on whatever file you were looking at previously - it won't search the current file until you click in the new file's window.  Maybe the quick file find needs to focus the new window?

**Comment by pkulchenko** [comment] 2016-01-03 18:04
@WhiteNoise, thank you for the report. I can't reproduce the issue. Here is what I've tried (on Windows):

1. Ctrl-P
2. Select one of the files not currently open (I tried both file from a different tab and a new file).
3. Ctrl-F to search in the file. The search correctly occurs in the currently selected tab.

What OS are you using and what ZBS version are you using?

**Comment by pkulchenko** [comment] 2016-01-07 20:15
@WhiteNoise, do you have any additional information on this as I'm not able to reproduce per my earlier message?

**Comment by pkulchenko** [comment] 2016-01-20 01:37
@WhiteNoise, I'm closing this; reopen if you have more information for me to reproduce.

**Comment by WhiteNoise** [comment] 2016-01-23 16:02
Hi, sorry for the delay. I'm on the Mac and I'm using the latest code from the github repo. I just updated to make sure and the issue is still there.

**Comment by pkulchenko** [comment] 2016-01-23 17:35
@WhiteNoise, yes, I can reproduce it on OSX; I'll check on what's going on there...

**Comment by pkulchenko** [comment] 2016-01-25 02:55
@WhiteNoise, should be fixed now. Give it a try and let me know how it works for you. This also fixes couple of side-effects of the same issue (for example, after selection in the command bar, typing into editor wouldn't work without clicking on it).

**Closed** 2016-01-25 02:54 UTC
Labels: Bug

**Comment by WhiteNoise** [comment] 2016-01-28 13:24
That fixed it - thanks so much!
