### ISSUE TITLE
Error problems using this package.

### ISSUE THREAD

**Issue by Cooolaid** [pkulchenko/ZeroBraneStudio#510] opened 2015-08-10 04:36 UTC
I downloaded the ( .zip portable ) version latest Zerobrane from the website and installed it on thumbdrive.
I then came here and downloaded this package (.zip) file.
I overwritten the installed package that's on my thumbdrive with this one, to get the dark theme.
only to get this when I go to [[ Edit>Preferences>and then to Settings:Systems or Settings:User ]]
only to get a crash like this:

http://i.imgur.com/c4nG6Uf.jpg

All I want to do it get this blinding white theme off my computer as its blinding the crap out of my eyes.
I want this on Windows 7 x64 bit. SP1

http://i.imgur.com/BVbR46w.png

**Comment by madmaxoft** [comment] 2015-08-10 05:31
Is it possible that you have edited your system config file and that change makes ZBS fail? Try commenting out the contents of the file, or renaming it so that ZBS starts clean.

**Comment by pkulchenko** [comment] 2015-08-10 05:32
@madmaxoft, it's the problem in the IDE. I should have a fix in a minute.

**Comment by pkulchenko** [comment] 2015-08-10 05:34
@Cooolaid, thank you for the report. Should be fixed now.

The problem is not with the package, but you should be able to open a configuration file properly now.

**Closed** 2015-08-10 05:33 UTC

**Comment by Cooolaid** [comment] 2015-08-10 05:59
@pkulchenko , Im glad I can help :) & you're very welcome...
