### ISSUE TITLE
Search keywords cannot be changed

### ISSUE THREAD

**Issue by current1990** [pkulchenko/ZeroBraneStudio#545] opened 2015-10-22 10:08 UTC
I used Ctrl+F to search something in source file and press ESC to close search bar
Next time when Ctrl+F is pressed it keeps searching next matching for previous key word. The only way to call the search bar out is through Menu items

I'm using ArchLinux
With zerobrane version (devel; MobDebug 0.62)

Thanks

**Comment by pkulchenko** [comment] 2015-10-22 15:07
@current1990, I don't have ArchLinux VM to try on at the moment, but I'm a bit confused as `Ctrl+F` is not supposed to initiate a search. It should only open a search panel if it's not open already (or refresh it if it was open as a different type of search). Are you thinking about `F3` perhaps?

Or maybe describe the steps you are doing in a bit more detail (as well as the expected results). Thanks.

**Comment by current1990** [comment] 2015-10-22 15:14
Hi pkulchenko

Let me make it more specified :)

Step 1, I pressed Ctrl+F to open a search panel.

Step 2, I entered some keywords in the search panel and pressed Enter and the search begins, after that i pressed enter several more times to find other matches

Step 3, I pressed ESC to close the search panel

Step 4, I pressed Ctrl+F again, but the search panel didn't appear, it just begin searching the key word I entered in step 2. After that, Everytime when Ctrl+F is pressed, it searches next pattern matching the key word

Thanks

**Comment by pkulchenko** [comment] 2015-10-22 15:26
Now it's all clear ;). Can't say it's the intended behavior, but I'll need to figure out what's going on when I get access to my Arch VM. It's possible that the presence of the panel is mis-detected in your case. Can you apply the following patch and send me the output during Step 4? Thanks.

```diff
diff --git a/src/editor/findreplace.lua b/src/editor/findreplace.lua
index 2bfa7ad..a52dd84 100644
--- a/src/editor/findreplace.lua
+++ b/src/editor/findreplace.lua
@@ -1083,6 +1083,7 @@ function findReplace:refreshPanel(replace, infiles)
 
   local mgr = ide:GetUIManager()
   local pane = mgr:GetPane(searchpanel)
+DisplayOutputLn("searchpanel:IsShown", pane:IsShown())
   if not pane:IsShown() then
     local size = ctrl:GetSize()
     pane:Dock():Bottom():BestSize(size):MinSize(size):Layer(0):Row(1):Show()
```

**Comment by current1990** [comment] 2015-10-22 15:46
Hi,
I applied the patch. 
In Step 1, when Ctrl+F is pressed, output shows "searchpanel:IsShown	false"
In Step 4, when I pressed Ctrl+F, nothing appears in output and the behavior is still searching for next matching.
 
Thanks

**Comment by pkulchenko** [comment] 2015-10-22 16:09
ok; thank you. This seems to be something ArchLinux-specific as I tested on other Linux flavors I have and they work as expected (the panel is re-opened in step 4). I should be able to test on Arch later today.

**Comment by pkulchenko** [comment] 2015-10-22 21:21
@current1990, I can't reproduce this on the latest version of ArchBang Linux. I'm running it in a VM, so some key mappings may be off, but `Ctrl+F` is working as expected every time for me. What I noticed though is that `Super-F` (this is `Cmd-F` for me as I run the VMs on OSX) also opens the search panel, but only the first time. The subsequent times nothing (seemingly) happens, so it does look similar to what you are describing, but with a different key combination. If that's indeed the case, I'd close this as `Ctrl-F` works as expected for me.

Are you running this in a VM and are you indeed using `Ctrl-F` to open the panel?

**Comment by current1990** [comment] 2015-10-23 02:21
Yes, I run the ArchLinux VM on OSX 10.11 with VMWare Fushion. And super+F acts abnormal.

**Comment by pkulchenko** [comment] 2015-10-23 03:39
So, to confirm, the original question was about `super+F`, not `Ctrl-F`. `Ctrl-F` is working every time for me and behaves as expected.

I'm going to take a quick look at `Super+F` issue, but I'm not going to spend much time on this as this is very platform specific and is not planned to work.

**Comment by pkulchenko** [comment] 2015-10-25 04:49
@current1990, closing if the issue is about `Super+F` as I don't expect that combination to work and it probably works by coincidence. Reopen if the issue is about `Ctrl-F`.

**Closed by pkulchenko** 2015-10-25 04:49 UTC
