### ISSUE TITLE
Icons missing on Linux

### ISSUE THREAD

**Issue by qubodup** [pkulchenko/ZeroBraneStudio#646] opened 2016-05-24 12:30 UTC
I extracted the zbstudio .sh file using `7z x` to get the app folder because it required sudo and I need a portable editor. This is probably not intended use and might invalidate this ticket.

When I start zbstudio, this is what I see:
![1464092485-](https://cloud.githubusercontent.com/assets/18312/15503624/15736598-21bb-11e6-978f-bf71c96e1950.png)

The "close tab" icon is missing.

There might be other UI elements missing (borders around tabs/widgets) but I can't tell for sure.

I'm on 64 bit Arch Linux and use the Adwaita GTK theme.

The fault might be of course misconfiguration of my system. I have no way of testing this on another Linux system right now but will do once I get a chance.

**Comment by CapsAdmin** [comment] 2016-05-24 13:32
The close button is visible here using KDE.

**Comment by pkulchenko** [comment] 2016-05-24 14:28
@qubodup, it's a duplicate of #306. Should be fixed by #260 when it's complete. You may want to try the wxwidgets31x-upgrade branch from the repository as I expect it to be fixed there.

**Closed by pkulchenko** 2016-05-24 14:28 UTC
