### ISSUE TITLE
Unfold current scope w/other folds modifier key (macOS)

### ISSUE THREAD

**Issue by Disco88** [pkulchenko/ZeroBraneStudio#828] opened 2017-11-06 18:58 UTC
With the newer MacBook laptops the (command)+(shift)+ click modifier key doesn't work when using laptops built in keyboard in order to expand the scope including all of the child scopes inside.

- Using an external keyboard works fine.
- Im not sure if its not registering the cmd+shift or if its not counting the mouse click. 
- Its most likely the cmd+shift combo that is being over-ridden by something when only using the built in keyboard.
- I checked all of my modifier keys in macOS and the only ones that are mapped to cmd+shift are the screenshot modifiers. cmd+shift+4 etc... I wouldn't think that would affect the modifier keys cmd & shift though.

Maybe try changing the modifier key to just Shift +FoldMarginClick to expand the scope with all other scopes to see if that works?

Thanks

**Comment by Disco88** [comment] 2017-11-06 19:09
Here's a reference to another issue that seems to be dealing with the same thing.

https://github.com/mattanger/ckb-next/issues/29

**Comment by pkulchenko** [comment] 2017-11-06 19:30
@Disco88, interested; thank you for the detailed analysis. I'll have to think about a mechanism to allow `something+click` shortcuts to be configurable.

**Comment by pkulchenko** [comment] 2017-11-07 06:00
@Disco88, `Shift-Click` is already taken (see #653 for related discussion), but after checking the code and my notes, I'm thinking it's possible to change it to use `Ctrl`, not `Cmd` on MacOS as well, so it should probably be `RAW_CONTROL` instead. Can you try the following patch:

```diff
diff --git a/src/editor/editor.lua b/src/editor/editor.lua
index 1ce581f..65581fa 100644
--- a/src/editor/editor.lua
+++ b/src/editor/editor.lua
@@ -862,7 +862,7 @@ function CreateEditor(bare)
       elseif marginno == margin.FOLD then
         local header = bit.band(editor:GetFoldLevel(line),
           wxstc.wxSTC_FOLDLEVELHEADERFLAG) == wxstc.wxSTC_FOLDLEVELHEADERFLAG
-        local shift, ctrl = wx.wxGetKeyState(wx.WXK_SHIFT), wx.wxGetKeyState(wx.WXK_CONTROL)
+        local shift, ctrl = wx.wxGetKeyState(wx.WXK_SHIFT), wx.wxGetKeyState(wx.WXK_RAW_CONTROL)
         if shift and ctrl then
           editor:FoldSome(line)
         elseif ctrl then -- select the scope that was clicked on
```

The documentation will need to be updated as well if this change is committed.

**Comment by pkulchenko** [comment] 2017-11-10 00:20
@Disco88, do you have more information about your MacBook? I've tried on a couple of fairly recent machines and can't reproduce this issue as the `Cmd+Shift+Click` combination works as expected on the builtin keyboard.

I'm closing for now as the effect is limited and there is a workaround, but I'm thinking maybe a better fix will be to use `wx.wxGetKeyState(wx.WXK_CONTROL) or wx.wxGetKeyState(wx.WXK_RAW_CONTROL)`.

**Closed by pkulchenko** 2017-11-10 00:20 UTC
