### ISSUE TITLE
Unable to debug redis lua script

### ISSUE THREAD

**Issue by rvnath** [pkulchenko/ZeroBraneStudio#664] opened 2016-07-13 17:51 UTC
Hi,
I installed redis lua plugin and tried to debug a lua script.  It is inconsistent.  Most of the times it gives me an error 
> reading error: timeout

This happens on a linux mint / Ubuntu 64bit m/c.  On a windows m/c it seems to work fine.

**Comment by rvnath** [comment] 2016-07-13 17:53
![lua](https://cloud.githubusercontent.com/assets/4309494/16813788/bbf91400-4950-11e6-9617-25e9d648e91c.png)

**Comment by pkulchenko** [comment] 2016-07-13 21:22
@rvnath, you may try setting `redis.verbose = true` to see the messages being sent and receive, which may provide additional details as to when the timeout happens.

@itamarhaber, any ideas what may be causing this on the redis side?

**Comment by itamarhaber** [comment] 2016-07-14 09:55
Nope - checked with lead dev and tried reproducing locally to no avail.

@rvnath - which Redis version do you have installed?

**Comment by rvnath** [comment] 2016-07-15 14:05
I grabbed the latest 3.2.  However, before doing that, I had the previous version of Redis running. I shutdown that downloaded the latest and started it again.  From another terminal I was starting the debugger editor.  I will once again check, after restarting the server today.

**Comment by itamarhaber** [comment] 2016-07-15 14:13
I was using the unstable tip so I switched to the latest 3.2 and still could not reproduce.

@rvnath be sure to enable verbosity so we can nail this one, thank you ;)

**Comment by pkulchenko** [comment] 2016-08-16 04:45
@rvnath, closing for now; let us know if you have any additional information that may help in troubleshooting.

**Closed by pkulchenko** 2016-08-16 04:45 UTC

**Comment by rvnath** [comment] 2016-09-03 07:38
I am getting the same error on a new m/c with Redis 3.2.3 server and ZBstudio 1.40

Sorry for my naiviety, where and how do I set "redis.verbose=true"

**Comment by pkulchenko** [comment] 2016-09-03 15:34
@rvnath, you can go to `Edit | Preferences | Settings: User`, add `redis.verbose=true` to that file, and save it. Then restart the IDE and try again.

**Comment by rvnath** [comment] 2016-09-05 11:53
When I restart the IDE, I see an error message in the output pane as below:

> Error while processing configuration file: '/home/rvnath/.zbstudio/user.lua:5: attempt to index global 'redis' (a nil value)'.

And when I run my prog in debug model and try to inspect a value, it gives the error and terminates.

> Program starting as '"/opt/zbstudio/bin/linux/x64/lua" "/opt/zbstudio/packages/redis.lua" --instance redis://localhost:6379 --controller admin:8172 --debug yes "/home/rvnath/projects/comviva/mbs/ecp7/dev/javascript/campaign_service/scripts/is_running.lua"  , 12'.
> Program 'lua' started in '/opt/zbstudio/myprograms' (pid: 24854).
> Debugging session started in '/opt/zbstudio/myprograms/'.
> reading error: timeout
> Program completed in 15.13 seconds (pid: 24854).

Is there anything [else] that I should look at?  Just fyi, if I use the normal command line debugger as suggested by Redis Labs it was | is working correctly.

> redis-cli --ldb --eval ./is_running.lua 0 , system:settings:global:databases:ecpDB
With the above command, I have/had always been able to work correctly in debug mode.  Only that ZB is not working.

**Comment by pkulchenko** [comment] 2016-09-05 16:52
@rvnath, my bad, try `redis = {verbose = true}` instead of `redis.verbose=true`.

Based on the error, it seems like the client times out on the first attempt to read from the Redis instance. Is the Redis instance running on `localhost` at 6379? I can't think of anything that would make it fail on the first read...

**Comment by rvnath** [comment] 2016-09-07 09:48
Yes, it is running on localhost:6379.

Here is the verbose output:

> Program starting as '"/opt/zbstudio/bin/linux/x64/lua" "/opt/zbstudio/packages/redis.lua" --instance redis://localhost:6379 --controller admin:8172 --debug yes --verbose "/home/rvnath/projects/comviva/mbs/ecp7/dev/javascript/campaign_service/scripts/get_state.lua"  , 12'.
> Program 'lua' started in '/opt/zbstudio/myprograms' (pid: 20141).
> <redis sent> *1\r\n$4\r\nPING\r\n
> <redis rcvd> +PONG
> <redis sent> *2\r\n$4\r\nINFO\r\n$6\r\nSERVER\r\n
> <redis rcvd> $449
> <redis rcvd> # Server\r\nredis_version:3.2.3\r\nredis_git_sha1:00000000\r\nredis_git_dirty:0\r\nredis_build_id:aaf92c3aed47b628\r\nredis_mode:standalone\r\nos:Linux 4.4.0-21-generic x86_64\r\narch_bits:64\r\nmultiplexing_api:epoll\r\ngcc_version:5.3.1\r\nprocess_id:923\r\nrun_id:3ac09613767f612ee740f7dab317121114458dd1\r\ntcp_port:6379\r\nuptime_in_seconds:1360502\r\nuptime_in_days:15\r\nhz:10\r\nlru_clock:13623722\r\nexecutable:/usr/local/bin/redis-server\r\nconfig_file:/etc/redis/6379.conf\r\n\r\n
> <redis sent> *3\r\n$6\r\nSCRIPT\r\n$5\r\nDEBUG\r\n$3\r\nyes\r\n
> <redis rcvd> +OK
> <redis sent> *4\r\n$4\r\nEVAL\r\n$329\r\nlocal jobId = KEYS[1]\nlocal jobExists = redis.pcall('exists', jobId)\nif jobExists == 0 or jobExists == nil then\n  return 404  -- not found.\nend\n\n-- check the job state\nlocal st = tonumber(redis.pcall('hmget', jobId, 'ctlState')[1])\nif st == nil then\n  st = 12002  -- job running, unless explicitly stated otherwise\nend\nreturn st\n\r\n$1\r\n0\r\n$2\r\n12\r\n
> <redis rcvd> *2
> <redis rcvd> +* Stopped at 1, stop reason = step over
> <redis rcvd> +-> 1   local jobId = KEYS[1]
> <redis sent> *2\r\n$1\r\nB\r\n$1\r\n0\r\n
> <redis rcvd> *1
> <redis rcvd> +All breakpoints removed.
> Debugging session started in '/opt/zbstudio/myprograms/'.
> <redis sent> *1\r\n$1\r\nS\r\n
> <redis rcvd> error: timeout
> reading error: timeout
> Program completed in 11.70 seconds (pid: 20141).
> Debugging session completed (traced 0 instructions).
>

**Comment by pkulchenko** [comment] 2016-09-07 23:20
@rvnath, thank you for the details. I don't see anything wrong up to the timeout error. It seems like it doesn't get any response to the "step" command.

Are you sending any KEYS? Based on the command, it seems like you don't provide any KEYS and only provide `12` as ARGV. I think it may cause an error, but I'm not sure why the error is not reported back. @itamarhaber, any ideas?

**Comment by rvnath** [comment] 2016-09-08 03:36
Previously, I was using only args. Later I tried with sending keys instead of args.  But there is no change in the behaviour.
![zb](https://cloud.githubusercontent.com/assets/4309494/18336253/43b1001e-75a3-11e6-8bb1-613f5ba4ef7c.png)

**Comment by pkulchenko** [comment] 2016-09-08 03:42
So, the debugger does execute the step? As you said before, it sometimes works and sometimes doesn't?

**Comment by itamarhaber** [comment] 2016-09-20 13:12
@pkulchenko no ideas yet, will try to reproduce reliably - I've seen a timeout a few times too but haven't Lua-ed in a while (Redis modules are keeping us busy ;))

**Comment by pkulchenko** [comment] 2016-09-20 15:30
thanks @itamarhaber; any additional info you can provide will help.

**Comment by UASFILG** [comment] 2016-11-06 21:35
I got exactly the same issue. 
The root cause is the timeout set at redis.lua file at line 1745
-- connect to redis instance
local ok, err = pcall(redis.connect, {host = host, port = port, timeout = 5.5})

In order to have some free time for debugging I changed the timeout to 30 seconds
local ok, err = pcall(redis.connect, {host = host, port = port, timeout = **30**})

Now it is running perfectly well !!!

**Comment by pkulchenko** [comment] 2016-11-06 23:27
@Filgs, very interesting. I think I picked the value myself, but I'm not sure it's the most optimal value.

@itamarhaber, should we set it to 30 seconds as @Filgs suggested or is there a better setting?

**Comment by rvnath** [comment] 2016-11-10 13:00
So, does this mean that I have to finish debugging within 30 secs?

**Comment by pkulchenko** [comment] 2016-11-10 17:33
@rvnath, as far as I understand, no, as the timeout should be per command, but still checking...

**Comment by pkulchenko** [comment] 2016-11-10 17:36
@Filgs, I wonder if we need that timeout setting at all. Can you try setting it to `nil`, as it should block indefinitely in this case?

**Comment by Filgs** [comment] 2016-11-12 13:44
@pkulchenko, I have just tested setting timeout to nil at line 1745 of redis.lua
local ok, err = pcall(redis.connect, {host = host, port = port, timeout = **nil**})

Now the debugging timeout is endless !!!
See below a step by step debugging session of 1145 seconds 
Program completed in  = **1145.11** seconds (pid: 3036).
Debugging session completed (traced 8 instructions).

Just one comment, the 30 seconds timeout was working for a complete step by step debugging session, not for each Lua statement. So it was a temporary solution which worked fine for me.

@rvnath
Please change the timeout to nil and get all the time available for your debugging session (including coffee).
The file is located at /opt/zbstudio/packages/redis.lua in my Ubuntu machine.

**Comment by rvnath** [comment] 2016-11-15 05:04
vow. This is good!  It works now.
I found two instances of this variable timeout on lines 1480 and 1745 respectively. I changed both of them to nil.

**Comment by pkulchenko** [comment] 2016-11-20 06:56
@rvnath, yes, I updated the one on line 1745, but you probably don't need to change anything on line 1480 as it's only for the initial check, which has no influence on the debugging (in fact, you may want to keep that one short in case there is nothing at the port/address that is being checked).
