### ISSUE TITLE
Copy and paste issue in multi-line Lua comments

### ISSUE THREAD

**Issue by Silverlan** [pkulchenko/ZeroBraneStudio#827] opened 2017-10-30 16:12 UTC
This is a bit of an odd one, I've recorded a video here: https://youtu.be/yGfDMqiq-p0
If I try to copy and paste the line "auto fGetLocalTransform = [](const Node* node, btTransform& act) {" into a multi-line Lua comment block in ZeroBrane, part of the line isn't being pasted properly.

**Comment by pkulchenko** [comment] 2017-10-30 16:26
@Silverlan, it's the result of markdown markup being processed in comments. `[]()` is recognized as a link, but the description is empty, so you don't actually see any link. The text is actually there, it's just made hidden to not show the markup. You can remove the starting comment (to make the text appear).

I'll check on whether the matching can be improved to not match `[]` when it's empty, but the current result is more or less by design ;).

**Comment by pkulchenko** [comment] 2017-10-30 22:12
Should be fixed now. Thanks for the report.

**Closed** 2017-10-30 22:12 UTC
