### ISSUE TITLE
Back / Forward Button

### ISSUE THREAD

**Issue by Kdansky** [pkulchenko/ZeroBraneStudio#699] opened 2016-09-22 11:02 UTC
Visual Studio has this great feature where you have a "back" button to jump back to where you were looking earlier. It is especially useful to use "Go To Definition", look at said definition, and then immediately jump back to where you come from.

I am not sure how exactly it works, as it can even deal with scrolling and opening different files. It always kinda makes sense.

**Comment by pkulchenko** [comment] 2016-09-22 15:34
This looks like a duplicate of #690. See the discussion there.

With Go To Definition it already works as you can use `Alt-Left` combination to jump back to the original location (see #203).

**Closed by pkulchenko** 2016-09-22 15:34 UTC
