### ISSUE TITLE
Double clicking in Stack window no longer opens the file for the stack frame

### ISSUE THREAD

**Issue by toturi** [pkulchenko/ZeroBraneStudio#608] opened 2016-03-16 01:54 UTC
With latest pull from repository (as of 6pm PST March 15, 2016), double clicking in the Stack window while the app is suspended no longer opens the file in the IDE. I believe this problem may have been introduced prior to the time stamp above. This was observed on OS X Yosemite (10.10.5), while debugging a Corona SDK application.

When I used the 1.30 release, double clicking a stack frame does open the file for that context.

Using the following test code:

-----
function shutdown()
  print('Calling shutdown()')
end

function exit()
  print('Calling exit')
  shutdown()
end

exit()
-----

Steps to reproduce (assumes you already have a project directory set):
1) Set a breakpoint on the line "print('Calling shutdown()')" in the code above.
2) Press F5 or click the Debug button in the IDE.
3) Upon hitting the breakpoint, double click any stack frame context row in the Stack window and observe the editor window does not switch to the line matching the stack frame. Alternatively, if the file is not already open, observe that double clicking does not open the file in the editor.

**Comment by pkulchenko** [comment] 2016-03-16 02:10
@toturi, thank you for the report. This was indeed caused by a recent debugger redesign and should be fixed now. Let me know if you notice any other issues.

**Closed** 2016-03-16 02:09 UTC
Labels: Bug

**Comment by toturi** [comment] 2016-03-16 02:27
@pkulchenko Confirmed Stack window double click works again. Thanks for the quick bug fix!
