### ISSUE TITLE
Strange CPU-Load issue when debugging and using wx

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#1010] opened 2019-09-14 11:39 UTC
Take this sample script
```lua
a=1
require"wx"
b=2
```
and set breakpoints on the two assignments to `a` and `b`

Press [F5] to debug, ZBS will stop at `a=1`  ¹)
There is no CPU load at all while script is stopped at the breakpoint.

Press [F5] again , ZBS will stop at `b=2`
But now there is a CPU-Load of 100% from ZBS while being stopped at the breakppoint...

This all with ZeroBrane Studio (1.80; MobDebug 0.705) on Ubuntu 18.04.3 LTS

¹) I have `debugger.runonstart = true` set

**Comment by pkulchenko** [comment] 2019-09-14 15:07
@jjvbsag, I suspect it may have something to do with the way debugging is done for wxlua-based apps. I couldn't get the IDLE event to get triggered on Linux, so I ended up using TIMER event every 10ms, but maybe it's too frequent, which loads the CPU.

Can you apply the following patch and see if the result changes:

```diff
diff --git a/lualibs/mobdebug/mobdebug.lua b/lualibs/mobdebug/mobdebug.lua
index c16a39c8..6f23a393 100644
--- a/lualibs/mobdebug/mobdebug.lua
+++ b/lualibs/mobdebug/mobdebug.lua
@@ -785,7 +785,7 @@ local function debugger_loop(sev, svars, sfile, sline)
           if win and not inloop then
             -- process messages in a regular way
             -- and exit as soon as the event loop is idle
-            if osname == 'Unix' then wx.wxTimer(app):Start(10, true) end
+            --if osname == 'Unix' then wx.wxTimer(app):Start(10, true) end
             local exitLoop = function()
               win:Disconnect(wx.wxID_ANY, wx.wxID_ANY, wx.wxEVT_IDLE)
               win:Disconnect(wx.wxID_ANY, wx.wxID_ANY, wx.wxEVT_TIMER)
```

If that doesn't work, then try changing 10 to something like 100 or 500 and see if it works better.

BTW, this logic only applies *before* the main loop has been started, which is normally when you'd want the debugging to happen.

**Comment by jjvbsag** [comment] 2019-09-18 16:45
Verified. Makes no difference

- original : high load at second breakpoint
- commented : high load at second breakpoint
- set timeout to 50000 (just to be sure :grin: ) : high load at second breakpoint

BTW: Are there any (other) sideeffects when debugging wx-applications which use EVT_IDLE and/or EVT_TIMER by themself?

Maybe we should have a look at the different cases:

- script not requiring "wx" at all
- script with require"wx", but does not really use it
- script with require"wx", but does only use not GUI or event driven methods (e.g. wx.wxFileName(),wx.wxDir() and similar)
- script with require "wx" and using times, events or GUI

Just as a starting point?

**Comment by pkulchenko** [comment] 2019-09-18 16:50
@jjvbsag, thank you for the update. I think we need to add and explore one more case: script with require "wx", but the breakpoint is set somewhere after MainLoop is already started, as it's likely to be the most frequent case.

What happens if you remove the breakpoint before the main loop is started and put it somewhere in one of the events (for example, on KEY_PRESS or TIMER event)? Does the CPU still show high usage?

**Comment by jjvbsag** [comment] 2019-09-20 09:03
@pkulchenko 
I created the following script to test your suggestion:
```
#!/usr/bin/lua
require"strict"
require"wx"

local cIdle,cTimer,cEvent=0,0,0

--
-- create the wx stuff
--
local frame=wx.wxFrame(wx.NULL,wx.wxID_ANY,"TEST",wx.wxDefaultPosition,wx.wxDefaultSize)
local panel=wx.wxPanel(frame,wx.wxID_ANY)
local sizer=wx.wxBoxSizer(wx.wxVERTICAL)
local tIdle=wx.wxStaticText(panel,wx.wxID_ANY,"---")
local tTimer=wx.wxStaticText(panel,wx.wxID_ANY,"---")
local bEvent=wx.wxButton(panel,wx.wxID_ANY, "Click")
local timer=wx.wxTimer(frame)

--
-- layout and show
--
sizer:Add(tIdle,0,wx.wxALL,5)
sizer:Add(tTimer,0,wx.wxALL,5)
sizer:Add(bEvent,0,wx.wxALL,5)
panel:SetSizer(sizer)
sizer:SetSizeHints(panel)
frame:Layout()
frame:Center()
frame:Show(true)

--
-- handlers
--
local function onIdle(event)
	cIdle=cIdle+1
	tIdle:SetLabel(tostring(cIdle))
	event:RequestMore()
	event:Skip()
end
local function onTimer(event)
	cTimer=cTimer+1
	tTimer:SetLabel(tostring(cTimer))
end
local function onEvent(event)
	cEvent=cEvent+1
	bEvent:SetLabel(tostring(cEvent))
end

--
-- connect
--
frame:Connect(bEvent:GetId(),wx.wxEVT_COMMAND_BUTTON_CLICKED,onEvent)
frame:Connect(wx.wxEVT_IDLE,onIdle)
frame:Connect(wx.wxEVT_TIMER, onTimer)
timer:Start(1000,wx.wxTIMER_CONTINUOUS)

--
-- main loop
--
wx.wxGetApp():MainLoop()
os.exit()
```
Of course, when the script is running, onIdle will create a cpu-load. But stopping the script by a breakpoint should return load near to zero.

But a breakpoint in onIdle, onTimer or onEvent will reproduce the initial issue. 
Question: Is it possible to debug and setbreakpoint _in_ ZBS _with_ ZBS ?

**Comment by pkulchenko** [comment] 2020-12-03 05:48
@jjvbsag, I'm closing this, as I can't reproduce this issue.

Also, it's possible to debug ZBS with ZBS, but you need to disable `singleinstance` check to allow multiple instances to be started. See https://studio.zerobrane.com/doc-faq#how-do-i-run-multiple-instances-of-zerobrane-studio

**Closed by pkulchenko** 2020-12-03 05:48 UTC
