### ISSUE TITLE
Live coding in Love2D broken

### ISSUE THREAD

**Issue by simonbroggi** [pkulchenko/ZeroBraneStudio#1164] opened 2023-09-06 11:56 UTC
When running a Love2D programm as Scratchpad, I get an error as soon as I change a value in the code.
Error message:

Scratchpad error on line 1:
[string "(function(...)function love.lo..."]:1: '=' expected near 'love'

**Comment by simonbroggi** [comment] 2023-09-07 07:24
I tried with the simple script from the tutorial.

`\ZeroBraneStudio\myprograms\LOVE-samples\trajectory\main.lua`

Does this work for you? Maybe there's something wrong with my installation? Thanks for the feedback.

**Comment by pkulchenko** [comment] 2023-09-08 04:47
I can confirm the issue; it appears to be caused by an upgrade to Mobdebug 0.801 (0a695ee4), but I'm not yet sure of the best fix. Will update shortly.

**Comment by pkulchenko** [comment] 2023-09-25 02:44
@simonbroggi, give the master branch a try; should be fixed now.

**Closed** 2023-09-25 02:44 UTC

**Comment by simonbroggi** [comment] 2023-09-25 12:17
I'll do that some time this week.
Thank you!!

**Comment by simonbroggi** [comment] 2023-09-28 11:52
it definitely works!
https://mastodon.gamedev.place/@smonbrogg/111142617000553203
:-)

**Comment by pkulchenko** [comment] 2023-09-29 02:37
Cool; that's great to gear! I released v2.01 with these changes. Thank you for confirming.
