### ISSUE TITLE
Can't delete commented out lines with DEL

### ISSUE THREAD

**Issue by xenomeno** [pkulchenko/ZeroBraneStudio#1111] opened 2021-03-27 22:34 UTC
If I have selected several lines of code and try to delete them with DEL it does not work if some of them are commented out, e.g. start with --

Using BACKSPACE or cut from the context menu works just fine. If the selected lines do not have commented out ones DEL works just fine.

![image](https://user-images.githubusercontent.com/38152099/112736704-5e320900-8f5d-11eb-8075-7896e1675846.png)

**Comment by pkulchenko** [comment] 2021-03-27 22:47
@xenomeno, thank you for the report. I don't think it's about the commented lines per se; I think it's related to the formatting inside those commented lines. Can you show the exact text you have in the comment with the minimal example?

**Comment by xenomeno** [comment] 2021-03-27 23:33
Hello,

Yes, I am attaching it as a ZIP. It seems it is because of the * symbols(don't seem so special to me though).

Hope this helps.
[DEL_Problem.zip](https://github.com/pkulchenko/ZeroBraneStudio/files/6216589/DEL_Problem.zip)

Cheers

**Comment by pkulchenko** [comment] 2021-03-27 23:53
Here is the code from the archive:

```lua
-- OK

-- NOT OK ******************************************************************
-- ******************************************************************
-- ******************************************************************


-- ***************
```

I can't reproduce the issue. I tried selecting various lines on both 1.90 and the current master and `Del` deletes selected lines without any issues. Can you describe what lines you have selected?

**Comment by xenomeno** [comment] 2021-03-28 07:28
If you select the first line marked with OK the deletion works. If you
select the one marked with Not OK it does not(the one with the * symbols).
It seems the lines containing * are causing the problem for me.

It is not a big issue and I can live with it. I am with some dark theme and
I can send you some configuration file if needed. My OS is Windows 10

Danko Jordanov
---------
https://vimeo.com/xenomeno/Terminator
https://vimeo.com/xenomeno/StuntDemo
http://www.imdb.com/name/nm1242406/
http://www.youtube.com/user/xenomeno79

**Comment by pkulchenko** [comment] 2021-03-28 18:08
For some reason I can't reproduce this issue. There are *some* combinations that won't work (for example, `ctrl-Backspace` should delete a word on the left of the cursor on Windows, but may not inside those comments with markup), but `Del` and `Backspace` always work for me. I'm closing this with Can't reproduce label, but if you have some additional details on this, feel free to update the ticket and I'll investigate.

**Closed by pkulchenko** 2021-03-28 18:08 UTC
