### ISSUE TITLE
Debugging issue with strict and wx

### ISSUE THREAD

**Issue by jjvbsag** [pkulchenko/ZeroBraneStudio#962] opened 2018-12-27 11:16 UTC
I have some issue debugging a (huge) script using wx in combination with strict. I could reduce the issue to a miminal testcase:

Take this simple script
```lua
require"strict"
local dict={a="A",b="B"}
local A=1 -- <= breakpoint goes here
```
Set breakpoint, debug, open Remote console tab and enter `=dict`
The (expected) output is
```
=dict
{
  a = "A",
  b = "B"
}
```
Now change the script to
```lua
require"strict"
require"wx"
local dict={a="A",b="B"}
local A=1 -- <= breakpoint goes here
```
do the same test procedure, the output is
```
dict
test-debug.lua:4: /opt/zbstudio/lualibs/mobdebug/mobdebug.lua:842: variable '...' is not declared
stack traceback:
	test-debug.lua: in main chunk
```
and the debugging session is killed.

:gift: I could fix this issue by changing line 842 from mobdebug.lua from
```lua
          status, res = stringify_results(params, pcall(func, unpack(env['...'] or {})))
```
to
```lua
          status, res = stringify_results(params, pcall(func, unpack(rawget(env,'...') or {})))
```

Please review the fix.
Regards

---
This is with ZBS1.80 MobDebug 0.705 on xubuntu 18.04 LTS

**Comment by pkulchenko** [comment] 2018-12-28 03:30
@jjvbsag, I'm trying to confirm the issue, but it's working as expected for me when running your (second) script with lua and wx libraries that ship with the IDE.

What versions of wx and Lua are you using? Also, `...` value should not be missing, as they are assigned in the `capture_vars` function and have the empty table value by default.

Applying the patch will surely fix the issue, but I don't understand why the values would be missing...

**Comment by jjvbsag** [comment] 2018-12-28 06:51
I just verified on a clean VM.
- xubuntu 18.04.1LTS minimal setup
- git clone zerobranestudio
- create empty test folder with above test script
- copy strict.lua from https://raw.githubusercontent.com/pkulchenko/wxlua/wxwidgets311/wxLua/modules/lua-5.1/etc/strict.lua into the folder (there is no other strict.lua on the whole VM)
- run test:

as above: without wx passes, with wx fails

If I can assist in any way, let me know :handshake:

**Comment by pkulchenko** [comment] 2018-12-28 06:58
Strange. I tried on Windows with the same setup and the same strict.lua and don't get that results. I don't have access to my Linux VMs at this time, but will try this weekend. Thanks for confirming!

**Comment by jjvbsag** [comment] 2019-11-07 07:59
@pkulchenko just verified with current branch `all-binaries-190c`. Issue is still reproducible.

**Comment by pkulchenko** [comment] 2019-11-07 15:40
Yes, mobdebug already includes the fix you suggested, I just need to upgrade the version bundled with the IDE. Will do shortly.

**Comment by pkulchenko** [comment] 2019-11-08 16:34
This is utterly confusing. I can't reproduce it on Windows, but I can reproduce it on Linux. I've tried to debug it, but I still can't figure out what could be causing this behavior. I plan to apply the fix, as I don't see any harm in it and in fact there may be some legitimate scenarios that would be fixed with the patch, but this behavior is not something I'd expect with this sample. Puzzling...

**Comment by pkulchenko** [comment] 2019-11-26 02:57
@jjvbsag, should be fixed. Let me know if you run into any further issues.

**Closed** 2019-11-26 02:57 UTC
Labels: Bug
