### ISSUE TITLE
Change tab cycling behavior

### ISSUE THREAD

**Issue by 4aiman** [pkulchenko/ZeroBraneStudio#782] opened 2017-07-24 16:37 UTC
Almost any other IDE uses ctrl+tab as a "return to previous tab"  shortcut.
How about implementing that with ZeroBrane?

It happens like this:
* press ctrl
* press tab
* release both

This effectively lets user to switch back and forth between two tabs.

In case there's a need to cycle through the opened tabs, one should do this:
* press ctrl and hold it
* press tab as many times as needed
* release both

Does ZeroBrane use some kind of a list to control which tab is the next?

In my opinion the changes in question can be done by adding last used tab to the first place in such a list.

**Comment by pkulchenko** [comment] 2017-07-24 17:18
It's a duplicate of #301; see that ticket and #66 for related discussion and alternatives.

**Closed by pkulchenko** 2017-07-24 17:18 UTC
