### ISSUE TITLE
IDE output displays fault on non ASCII characters from interpret

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#804] opened 2017-09-16 01:33 UTC
See different output from each windows of the same script (path and content both contain non ASCII characters).
The fram on picture is some non ASCII characters like Chinese, orange frame displays correctly, but in IDE the red frame is some messy character.
This time problem made artificially is more clear and typical.
- IDE
![image](https://user-images.githubusercontent.com/7419030/30508102-71211ac2-9ac1-11e7-8e6b-79408a15f835.png)
- lua.exe
![image](https://user-images.githubusercontent.com/7419030/30508158-b90d352c-9ac2-11e7-915a-59ddb4978f2e.png)
- cmd.exe
![image](https://user-images.githubusercontent.com/7419030/30508154-a6d1f19a-9ac2-11e7-8050-fc98a0c76f66.png)

**Comment by pkulchenko** [comment] 2017-09-16 04:47
It's a duplicate of #710. Not sure what to do about it as it looks like a difference in the charset and I can't reproduce it on my machine.

Can you copy the correct message to the comment itself (so I can copy it into the script and check its binary codes)?

**Comment by robertlzj** [comment] 2017-09-16 05:32
You mean this?
- From `lua.exe`
```
dofile[[C:\Users\RobertLin\Desktop\测试\test.lua]]
error loading module 'iuplua' from file '.\iuplua\iuplua51.dll':
        找不到指定的模块。

stack traceback:
        [C]: at 0x66df0a68
        [C]: in function 'require'
        C:\Users\RobertLin\Desktop\测试\test.lua:2: in main chunk
        [C]: in function 'dofile'
        stdin:1: in main chunk
        [C]: at 0x00401b00
```
- From `cmd` ( Codepage 936 ANSI/OEM simplified Chinese GBK from Property dialog )
```
C:\Users\RobertLin\Desktop\测试>lua C:\Users\RobertLin\Desktop\测试\test.lua
lua: error loading module 'iuplua' from file '.\iuplua\iuplua51.dll':
        找不到指定的模块。

stack traceback:
        [C]: at 0x66df0a68
        [C]: in function 'require'
        C:\Users\RobertLin\Desktop\测试\test.lua:2: in main chunk
        [C]: at 0x00401b00
```

**Comment by pkulchenko** [comment] 2017-09-16 05:42
Yes, that's what I was looking for. You are correct, you described this issue in #663, which included other issues as well and they have all been fixed except the error messages from the interpreter itself. All this information is helpful, but I'm not yet sure how to reproduce this issue locally, so I can research a possible fix.

**Comment by robertlzj** [comment] 2017-09-16 06:01
Maybe a virtual machine with different language/Codepage? 

**And** I had checked the #663 a little
> print("程序 файл") execute and output correct as it is - 程序 файл. (The problem occured in message from interpreter when code error?)

Find where IDE use **short name/path** to treat it.
See `C:\Users\ROBERT~1\Desktop\..\test.lua:2: in main chunk` (I can't copy/paste messy characters at `..`), compare to the correct one `C:\Users\RobertLin\Desktop\测试\test.lua:2: in main chunk`

**Comment by robertlzj** [comment] 2017-09-17 05:34
Additional test.
Without `user.lua`. Test script is `assert(false)`.
- F5 to Debug: 
![image](https://user-images.githubusercontent.com/7419030/30518291-664ac8d2-9bac-11e7-9a71-b3ed7b81130b.png)
- F6 to Run:
![image](https://user-images.githubusercontent.com/7419030/30518295-735a5f92-9bac-11e7-9c4c-93796ea5dbaa.png)
So error displayed character appears under shot path/name? ( as previous comment above)

**Comment by pkulchenko** [comment] 2017-09-17 06:00
Yes, your theory is correct; you can run the following in the console to get the correctly encoded characters: `winapi.encode(936, winapi.CP_UTF8, "\xb2\xe2\xca\xd4")`, but I'm still unsure where exactly it gets wrong as some characters are correct in the output and others are not.

**Comment by robertlzj** [comment] 2017-09-17 07:08
> where exactly it gets wrong as some characters are correct in the output and others are not.

"Others" that using 8.3 filename and short path in Run mode?

**Comment by pkulchenko** [comment] 2017-09-22 05:32
> "Others" that using 8.3 filename and short path in Run mode?

It doesn't seem to be related to this (or at least it's not the only reason), as it also happens with the error shown in the output panel.

You may try this patch:

```diff
diff --git a/src/editor/output.lua b/src/editor/output.lua
index ce30baf..241ad1c 100644
--- a/src/editor/output.lua
+++ b/src/editor/output.lua
@@ -133,6 +133,7 @@ end
 
 -- logic to "unhide" wxwidget window using winapi
 local ok, winapi = pcall(require, 'winapi')
+if not ok then winapi = nil end
 local checkstart, checknext, checkperiod
 local pid = nil
 local function unHideWindow(pidAssign)
@@ -141,7 +142,7 @@ local function unHideWindow(pidAssign)
   if pidAssign then
     pid = pidAssign > 0 and pidAssign or nil
   end
-  if pid and ok then -- pid provided and winapi loaded
+  if pid and winapi then -- pid provided and winapi loaded
     local now = TimeGet()
     if pidAssign and pidAssign > 0 then
       checkstart, checknext, checkperiod = now, now, 0.02
@@ -260,6 +261,11 @@ function CommandLineRun(cmd,wdir,tooutput,nohide,stringcallback,uid,endcallback)
   return pid
 end
 
+local codepage = tonumber(ide.config.codepage) or ide.config.codepage
+if codepage == true then
+  ide:ExecuteCommand("cmd /C chcp", nil, function(s) codepage = s:match("Active code page: (%d+)") end)
+end
+
 local readonce = 4096
 local maxread = readonce * 10 -- maximum number of bytes to read before pausing
 local function getStreams()
@@ -273,6 +279,11 @@ local function getStreams()
         str = str:sub(1, v.stream:LastRead())
         processed = processed + #str
 
+        if FixUTF8(str) == nil and winapi and codepage then
+          -- this looks like invalid UTF-8 content, which may be in a different code page
+          str = winapi.encode(codepage, winapi.CP_UTF8, str)
+        end
+
         local pfn
         if (v.callback) then
           str,pfn = v.callback(str)
```

You will need to set `codepage = true` (in which case it will try to auto-detect the codepage) or `codepage=936` (in which case you'll need to set it manually to match the output of `chcp`. I'd appreciate if you could test both settings.

Also, can you show me the full output of `chcp`? On my machine it shows `Active code page: ...`, but it may be something translated in your case, so I'm curious if I need to accommodate that.

**Comment by pkulchenko** [comment] 2017-09-22 05:40
The proposed patch doesn't address the filename issue during debugging (https://github.com/pkulchenko/ZeroBraneStudio/issues/559#issuecomment-319840861), but if it works, I'll see if I can extend it to cover that case as well.

**Comment by robertlzj** [comment] 2017-09-22 08:54
- I set `codepage = true` from `user.lua`, get this when IDE lunch etc ![image](https://user-images.githubusercontent.com/7419030/30736019-c49b02ca-9fb3-11e7-9ad1-c75ca22f8b74.png)
  Maybe you need to modify pattern in `s:match("Active code page: (%d+)") ` to match to local system? (`(Change to `(%d)+` don't solve it)
- Set `codepage=936`. Display is OK.
  ```
	Program starting as '"C:\ProgramFiles\ZeroBraneStudio\bin\lua53.exe" -e "io.stdout:setvbuf('no')" "C:\Users\ROBERT~1\OneDrive\文档\issue.lua"'.
	Program 'lua53.exe' started in 'C:\Users\RobertLin\OneDrive\文档' (pid: 34628).
	C:\ProgramFiles\ZeroBraneStudio\bin\lua53.exe: error loading module 'iuplua' from file 'C:\ProgramFiles\ZeroBraneStudio\bin\clibs53\iuplua53.dll':
		找不到指定的模块。


	stack traceback:
		[C]: in ?
		[C]: in function 'require'
		C:\Users\ROBERT~1\OneDrive\文档\issue.lua:2: in main chunk
		[C]: in ?
	Program completed in 0.11 seconds (pid: 34628).
  ```
- `chcp` is:
  ```
  C:\WINDOWS\system32>chcp
  活动代码页: 936
  ```
  I found it's an exe which could be ran directly from cmd.
- For #559 . IDE could open and run script, but can't debug, pop a windows dialog said `lua53.exe is stop to work`, then could close the dialog, IDE remains.

**Comment by pkulchenko** [comment] 2017-09-22 14:40
Yes, the error happens because the patch couldn't find the results in chcp output. I fixed this and also added a better check, so it should now detect it and not fail when it can't detect. Try this patch:

```diff
diff --git a/src/editor/output.lua b/src/editor/output.lua
index ce30baf..8c47d06 100644
--- a/src/editor/output.lua
+++ b/src/editor/output.lua
@@ -133,6 +133,7 @@ end
 
 -- logic to "unhide" wxwidget window using winapi
 local ok, winapi = pcall(require, 'winapi')
+if not ok then winapi = nil end
 local checkstart, checknext, checkperiod
 local pid = nil
 local function unHideWindow(pidAssign)
@@ -141,7 +142,7 @@ local function unHideWindow(pidAssign)
   if pidAssign then
     pid = pidAssign > 0 and pidAssign or nil
   end
-  if pid and ok then -- pid provided and winapi loaded
+  if pid and winapi then -- pid provided and winapi loaded
     local now = TimeGet()
     if pidAssign and pidAssign > 0 then
       checkstart, checknext, checkperiod = now, now, 0.02
@@ -260,6 +261,11 @@ function CommandLineRun(cmd,wdir,tooutput,nohide,stringcallback,uid,endcallback)
   return pid
 end
 
+local codepage = tonumber(ide.config.codepage) or ide.config.codepage
+if codepage == true then
+  ide:ExecuteCommand("cmd /C chcp", nil, function(s) codepage = s:match(":%s*(%d+)") end)
+end
+
 local readonce = 4096
 local maxread = readonce * 10 -- maximum number of bytes to read before pausing
 local function getStreams()
@@ -273,6 +279,11 @@ local function getStreams()
         str = str:sub(1, v.stream:LastRead())
         processed = processed + #str
 
+        if tonumber(codepage) and FixUTF8(str) == nil and winapi then
+          -- this looks like invalid UTF-8 content, which may be in a different code page
+          str = winapi.encode(codepage, winapi.CP_UTF8, str)
+        end
+
         local pfn
         if (v.callback) then
           str,pfn = v.callback(str)
```

**Comment by robertlzj** [comment] 2017-09-23 01:16
Test OK. Could use `codepage=true`.

**Closed** 2017-09-29 05:15 UTC
