### ISSUE TITLE
Dblclicking line with filename:line doesn't go to line

### ISSUE THREAD

**Issue by madmaxoft** [pkulchenko/ZeroBraneStudio#462] opened 2015-05-16 14:45 UTC
When there's a line in the output pane that starts with a "filename:line", doubleclicking that line opens the file, but doesn't set the cursor on the specified line.

This issue is only observed with files that are not yet open. Files that are already open (even in an inactive tab) seem to work properly. So double-clicking twice actually gets the job done in every case, but is rather unfriendly.

**Comment by pkulchenko** [comment] 2015-05-16 15:37
Mattes, I can't reproduce this issue. What's the format of the filename and the line number are you using? I tested on closed files with the following output and it works as expected:

```
D:\...\ZeroBraneStudio\bin\lua.exe: D:\...\test.lua:4: attempt to call global 'smth' (a nil value)
stack traceback:
	D:\...\test.lua:4: in main chunk
```

**Comment by madmaxoft** [comment] 2015-05-16 15:47
That's weird, now I can't reproduce this either. 
I had the output of the whole-project analyzer in the output, the filenames were full paths to files on a Windows filesystem.

**Comment by pkulchenko** [comment] 2015-05-16 17:16
But now these paths work? I've tried different combinations, but it works for me. I'm closing this, but if you can reproduce it, include the Output string on which it happens for me to test.

**Closed by pkulchenko** 2015-05-16 17:16 UTC

**Comment by madmaxoft** [comment] 2015-05-16 20:25
Ah, I may have found the reason. I was using ZBS from a USB stick and had an older version there, commit 57f3631687d97c153dfac5579657b5fbf250aa2d. That one is problematic with exactly the paths I provided before.
The ZBS version on my desktop is up to date and doesn't have the issue anymore, so I guess it has been already fixed. Sorry for that.
