### ISSUE TITLE
new tabs on debug lua embedded code

### ISSUE THREAD

**Issue by eugwne** [pkulchenko/ZeroBraneStudio#526] opened 2015-09-17 08:24 UTC
When I'am trying to debug an embedded code ZBS opens many tabs.

Tested on linux
User config : editor.autoactivate=true

Code with embedded lua to reproduce the case (main.c):

```C
#include <stdio.h>
#include <string.h>

#include <lua.h>
#include <lauxlib.h>
#include <lualib.h>

int main(void)
{
	const char * source = "local mobdebug = require('mobdebug') \n"
	"mobdebug.start() \n"

	"print('Start') \n"
	"local foo = 0 \n"
	"for i = 1, 3 do \n"
	  "local function bar() \n"
		"print('In bar') \n"
	  "end \n"
	  "foo = i \n"
	  "print('Loop') \n"
	  "bar() \n"
	"end \n"
	"print('End') ";

	lua_State *L = lua_open();
	luaL_openlibs(L);

	if (luaL_loadbuffer(L, source, strlen(source), source))
		  lua_error(L);

	if (lua_pcall(L, 0, 0, 0)) {
		lua_error(L);

	}

	printf("done!\n");
	return 0;
}
```

It's hard to workaround this case by saving source outside, because the source  always changes.

**Comment by pkulchenko** [comment] 2015-09-17 17:21
@eugwne, I don't see many tabs being opened. What I see is that when the new tab is opened (`untitled.lua`) and the debugging is started again, you get the message that you need to save the selected (unsaved) file. This is by design, but you have several simple workarounds: (1) you can close the current unsaved tab that was opened in the previous debugging session, (2) you can switch to any other tab that is not modified before starting debugging, or (3) you can save the current content into a file if you plan to re-use it later.

Essentially, the debugger requires the current tab to be saved into a file when starting a new debugging session. I'll see if this requirement can be relaxed when the debugging is starting externally, but you should easily work around it.

Let me know if I misunderstood the issue.

**Comment by eugwne** [comment] 2015-09-17 17:48
![screenshot from 2015-09-17 20 41 49](https://cloud.githubusercontent.com/assets/7532612/9941271/dfb41400-5d7c-11e5-9fe0-eb9fd48e1eda.png)

This happens when I run once. I start debugging server in ZBS, run my app, and while ZBS in backround it keeps opening tabs. I suppose that happens until ZBS main window is active, than it stops.

**Comment by pkulchenko** [comment] 2015-09-17 17:52
Hm, that's interesting as this is not what I see in my testing using your code. Do you use the latest version of the IDE from the master branch or do you run v1.10?

**Comment by eugwne** [comment] 2015-09-17 17:53
1.10 from site download page

**Comment by pkulchenko** [comment] 2015-09-17 18:04
Can you also confirm you get the same result on the current master branch? You can close or download the zip with the current version. Thanks!

Also, do the tabs continue to open as long as the IDE stays in the background? Could you add `DisplayOutputLn(file, line)` as the first line in `activateDocument` function in `debugger.lua` to see what parameters it's called with and how many times?

**Comment by eugwne** [comment] 2015-09-17 18:15
![image](https://cloud.githubusercontent.com/assets/7532612/9941943/18e22056-5d81-11e5-9ef5-40dc41b0606e.png)

cloned from master, the same

**Comment by eugwne** [comment] 2015-09-17 18:18
When I activated ZBS, as fast as I could, I had 4 tabs. So, I think it opens until activated

**Comment by pkulchenko** [comment] 2015-09-17 18:36
ok, can you also add the following line before `copas.setErrorHandler` call in `debugger.lua` (around line 560); I want to make sure that the client doesn't send multiple debugging requests: `DisplayOutputLn("started", debugger.server)`.

Are you using the same app you included in the first post?

Also, to help seeing where activation is called from, can you add `debug.traceback():gsub("\n", "; ")` to `DisplayOutputLn` call in `ActivateDocument`? Just show the output as text as it's easier to work with ;). Thank you.

**Comment by eugwne** [comment] 2015-09-17 18:55
Yes, this is the same app.

```
started	nil
"local mobdebug = require('mobdebug') \nmobdebug.start()\nprint('Start') \nlocal foo = 0 \nfor i = 1, 3 do \nlocal function bar() \nprint('In bar') \nend \nfoo = i \nprint('Loop') \nbar() \nend \nprint('End') "	3	stack traceback:; 	src/editor/debugger.lua:284: in function 'activateDocument'; 	src/editor/debugger.lua:686: in function <src/editor/debugger.lua:554>	2
Debugging session started in '/opt/zbstudio/myprograms/'.
"local mobdebug = require('mobdebug') \nmobdebug.start()\nprint('Start') \nlocal foo = 0 \nfor i = 1, 3 do \nlocal function bar() \nprint('In bar') \nend \nfoo = i \nprint('Loop') \nbar() \nend \nprint('End') "	3	stack traceback:; 	src/editor/debugger.lua:284: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'resume'; 	lualibs/copas/copas.lua:395: in function '_doTick'; 	lualibs/copas/copas.lua:421: in function 'def_tick'; 	lualibs/copas/copas.lua:512: in function 'tick'; 	lualibs/copas/copas.lua:620: in function 'step'; 	src/editor/debugger.lua:887: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: at 0x7fae9713f502; 	src/main.lua:724: in main chunk; 	[C]: at 0x004054e8	13
"local mobdebug = require('mobdebug') \nmobdebug.start()\nprint('Start') \nlocal foo = 0 \nfor i = 1, 3 do \nlocal function bar() \nprint('In bar') \nend \nfoo = i \nprint('Loop') \nbar() \nend \nprint('End') "	3	stack traceback:; 	src/editor/debugger.lua:284: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'resume'; 	lualibs/copas/copas.lua:395: in function '_doTick'; 	lualibs/copas/copas.lua:421: in function 'def_tick'; 	lualibs/copas/copas.lua:512: in function 'tick'; 	lualibs/copas/copas.lua:620: in function 'step'; 	src/editor/debugger.lua:887: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: at 0x7fae9713f502; 	src/main.lua:724: in main chunk; 	[C]: at 0x004054e8	18
"local mobdebug = require('mobdebug') \nmobdebug.start()\nprint('Start') \nlocal foo = 0 \nfor i = 1, 3 do \nlocal function bar() \nprint('In bar') \nend \nfoo = i \nprint('Loop') \nbar() \nend \nprint('End') "	3	stack traceback:; 	src/editor/debugger.lua:284: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	...; 	[C]: in function 'resume'; 	lualibs/copas/copas.lua:395: in function '_doTick'; 	lualibs/copas/copas.lua:421: in function 'def_tick'; 	lualibs/copas/copas.lua:512: in function 'tick'; 	lualibs/copas/copas.lua:620: in function 'step'; 	src/editor/debugger.lua:887: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: at 0x7fae9713f502; 	src/main.lua:724: in main chunk; 	[C]: at 0x004054e8	22
"local mobdebug = require('mobdebug') \nmobdebug.start()\nprint('Start') \nlocal foo = 0 \nfor i = 1, 3 do \nlocal function bar() \nprint('In bar') \nend \nfoo = i \nprint('Loop') \nbar() \nend \nprint('End') "	3	stack traceback:; 	src/editor/debugger.lua:284: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	...; 	[C]: in function 'resume'; 	lualibs/copas/copas.lua:395: in function '_doTick'; 	lualibs/copas/copas.lua:421: in function 'def_tick'; 	lualibs/copas/copas.lua:512: in function 'tick'; 	lualibs/copas/copas.lua:620: in function 'step'; 	src/editor/debugger.lua:887: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: at 0x7fae9713f502; 	src/main.lua:724: in main chunk; 	[C]: at 0x004054e8	22
"local mobdebug = require('mobdebug') \nmobdebug.start()\nprint('Start') \nlocal foo = 0 \nfor i = 1, 3 do \nlocal function bar() \nprint('In bar') \nend \nfoo = i \nprint('Loop') \nbar() \nend \nprint('End') "	3	stack traceback:; 	src/editor/debugger.lua:284: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	...; 	[C]: in function 'resume'; 	lualibs/copas/copas.lua:395: in function '_doTick'; 	lualibs/copas/copas.lua:421: in function 'def_tick'; 	lualibs/copas/copas.lua:512: in function 'tick'; 	lualibs/copas/copas.lua:620: in function 'step'; 	src/editor/debugger.lua:887: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: at 0x7fae9713f502; 	src/main.lua:724: in main chunk; 	[C]: at 0x004054e8	22
"local mobdebug = require('mobdebug') \nmobdebug.start()\nprint('Start') \nlocal foo = 0 \nfor i = 1, 3 do \nlocal function bar() \nprint('In bar') \nend \nfoo = i \nprint('Loop') \nbar() \nend \nprint('End') "	3	stack traceback:; 	src/editor/debugger.lua:284: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	...; 	[C]: in function 'resume'; 	lualibs/copas/copas.lua:395: in function '_doTick'; 	lualibs/copas/copas.lua:421: in function 'def_tick'; 	lualibs/copas/copas.lua:512: in function 'tick'; 	lualibs/copas/copas.lua:620: in function 'step'; 	src/editor/debugger.lua:887: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: at 0x7fae9713f502; 	src/main.lua:724: in main chunk; 	[C]: at 0x004054e8	22
"local mobdebug = require('mobdebug') \nmobdebug.start()\nprint('Start') \nlocal foo = 0 \nfor i = 1, 3 do \nlocal function bar() \nprint('In bar') \nend \nfoo = i \nprint('Loop') \nbar() \nend \nprint('End') "	3	stack traceback:; 	src/editor/debugger.lua:284: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	...; 	[C]: in function 'resume'; 	lualibs/copas/copas.lua:395: in function '_doTick'; 	lualibs/copas/copas.lua:421: in function 'def_tick'; 	lualibs/copas/copas.lua:512: in function 'tick'; 	lualibs/copas/copas.lua:620: in function 'step'; 	src/editor/debugger.lua:887: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: at 0x7fae9713f502; 	src/main.lua:724: in main chunk; 	[C]: at 0x004054e8	22
"local mobdebug = require('mobdebug') \nmobdebug.start()\nprint('Start') \nlocal foo = 0 \nfor i = 1, 3 do \nlocal function bar() \nprint('In bar') \nend \nfoo = i \nprint('Loop') \nbar() \nend \nprint('End') "	3	stack traceback:; 	src/editor/debugger.lua:284: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	...; 	[C]: in function 'resume'; 	lualibs/copas/copas.lua:395: in function '_doTick'; 	lualibs/copas/copas.lua:421: in function 'def_tick'; 	lualibs/copas/copas.lua:512: in function 'tick'; 	lualibs/copas/copas.lua:620: in function 'step'; 	src/editor/debugger.lua:887: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: at 0x7fae9713f502; 	src/main.lua:724: in main chunk; 	[C]: at 0x004054e8	22
"local mobdebug = require('mobdebug') \nmobdebug.start()\nprint('Start') \nlocal foo = 0 \nfor i = 1, 3 do \nlocal function bar() \nprint('In bar') \nend \nfoo = i \nprint('Loop') \nbar() \nend \nprint('End') "	3	stack traceback:; 	src/editor/debugger.lua:284: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	...; 	[C]: in function 'resume'; 	lualibs/copas/copas.lua:395: in function '_doTick'; 	lualibs/copas/copas.lua:421: in function 'def_tick'; 	lualibs/copas/copas.lua:512: in function 'tick'; 	lualibs/copas/copas.lua:620: in function 'step'; 	src/editor/debugger.lua:887: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: at 0x7fae9713f502; 	src/main.lua:724: in main chunk; 	[C]: at 0x004054e8	22
"local mobdebug = require('mobdebug') \nmobdebug.start()\nprint('Start') \nlocal foo = 0 \nfor i = 1, 3 do \nlocal function bar() \nprint('In bar') \nend \nfoo = i \nprint('Loop') \nbar() \nend \nprint('End') "	3	stack traceback:; 	src/editor/debugger.lua:284: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	...; 	[C]: in function 'resume'; 	lualibs/copas/copas.lua:395: in function '_doTick'; 	lualibs/copas/copas.lua:421: in function 'def_tick'; 	lualibs/copas/copas.lua:512: in function 'tick'; 	lualibs/copas/copas.lua:620: in function 'step'; 	src/editor/debugger.lua:887: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: at 0x7fae9713f502; 	src/main.lua:724: in main chunk; 	[C]: at 0x004054e8	22
"local mobdebug = require('mobdebug') \nmobdebug.start()\nprint('Start') \nlocal foo = 0 \nfor i = 1, 3 do \nlocal function bar() \nprint('In bar') \nend \nfoo = i \nprint('Loop') \nbar() \nend \nprint('End') "	3	stack traceback:; 	src/editor/debugger.lua:284: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	src/editor/debugger.lua:902: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: in function 'RequestUserAttention'; 	src/util.lua:387: in function 'RequestAttention'; 	src/editor/debugger.lua:355: in function 'activateDocument'; 	...; 	[C]: in function 'resume'; 	lualibs/copas/copas.lua:395: in function '_doTick'; 	lualibs/copas/copas.lua:421: in function 'def_tick'; 	lualibs/copas/copas.lua:512: in function 'tick'; 	lualibs/copas/copas.lua:620: in function 'step'; 	src/editor/debugger.lua:887: in function 'update'; 	src/editor/commands.lua:1030: in function <src/editor/commands.lua:1028>; 	[C]: at 0x7fae9713f502; 	src/main.lua:724: in main chunk; 	[C]: at 0x004054e8	22
```

**Comment by pkulchenko** [comment] 2015-09-17 19:22
I think I may know what's going on: `RequestAttention` seems to be calling (internally) handlers for idle callbacks, which in turn call `debugger.update()` and related processing. I don't see this happening on Windows and don't recall this happening on OSX either, so it appears to be Linux-specific.

Can you try the following patch:

```diff
diff --git a/src/editor/debugger.lua b/src/editor/debugger.lua
index 25e5160..80f7c89 100644
--- a/src/editor/debugger.lua
+++ b/src/editor/debugger.lua
@@ -889,6 +889,7 @@ do
     -- if there is any pending activation
     if debugger.activate then
       local file, line, content = unpack(debugger.activate)
+      debugger.activate = nil
       if content then
         local editor = NewFile()
         editor:SetText(content)
@@ -905,7 +906,6 @@ do
           activateDocument(file, line)
         end
       end
-      debugger.activate = nil
     end
   end
 end
```

**Comment by eugwne** [comment] 2015-09-17 19:31
Patch works, only one tab opens.

**Comment by pkulchenko** [comment] 2015-09-17 21:03
ok; should be fixed now. Thanks for the report.

**Closed** 2015-09-17 21:03 UTC
Labels: Bug
