### ISSUE TITLE
Sync save status of clone window

### ISSUE THREAD

**Issue by robertlzj** [pkulchenko/ZeroBraneStudio#619] opened 2016-03-26 15:04 UTC
When use clone window which get foucs, the cloned one will ask for save when run code/project, and if select save will get Save As dialog even if the original one is saved before (and if save directly from clone window, it's correct saved)

**Comment by pkulchenko** [comment] 2016-03-26 18:52
I think this particular issue has been fixed some time ago; make sure you are using the latest version of the `CloneView` plugin (0.13).

Also, if the issue is package/plugin related, please open it in its repository (in this case in https://github.com/pkulchenko/ZeroBranePackage/issues).

If upgrading to the latest version doesn't work for you, reopen the ticket.

**Comment by robertlzj** [comment] 2016-03-27 02:18
Yes, I used version 0.13.
It occurs when press F6 to run from cloned one. Popup, "Save file?" "You must save the program first. Press cancel to abort." If select yes will ask for Save As.
Ctrl+S will save without Save As.

**Comment by pkulchenko** [comment] 2016-04-17 16:41
@robertlzj, should be fixed now in the plugin (v0.14); give it a try.

**Closed** 2016-04-17 16:40 UTC
Labels: Plugin
