### ISSUE TITLE
ShowPosEnforcePolicy error from wxLua when doing a Find

### ISSUE THREAD

**Issue by dbaileychess** [pkulchenko/ZeroBraneStudio#406] opened 2015-02-02 21:46 UTC
OS: Win7 64-bit
ZBS: 0.95
wxLua: 2.8.12.2
wxWidgets: 2.9.5

Config: https://gist.github.com/dbaileychess/fa6414be62c06fc0423d

I tried to do a 'Find' on a source file and get the following error:

![image](https://cloud.githubusercontent.com/assets/1477247/6009700/03135446-aae1-11e4-96e1-1c1a4f17aef0.png)

It has occurred maybe 3 or 4 times today but I cannot exactly figure out what causes the error. I am able to use the Find dialog successfully many times but randomly I get this warning.

==EDIT==

I could reproduce it by doing this.

1) Run any Lua Script that prints to output
2) Double click on a word in the Output window
3) Ctrl-F
4) Click Find Next
5) Error appears

**Comment by pkulchenko** [comment] 2015-02-02 23:36
Derek, thank you for the report. This was indeed caused by the search initiated in the Output/Console panels. Should be fixed now.

**Closed** 2015-02-02 23:35 UTC

**Comment by joshua-scholar** [comment] 2015-02-22 21:37
I just got the same error. I'm using a brand new v0.95 .. I don't think the fix is in that.

**Comment by pkulchenko** [comment] 2015-02-22 21:41
@joshua-scholar, yes, this fix was checked in on Feb 2nd, after 0.95 was released. It will be included in the next version; you can also try the latest code from github (you can simply clone the repository or download and unpack the .zip archive).

**Comment by pkulchenko** [comment] 2015-02-22 21:42
The workaround is to switch focus to the editor tab (away from Output/Console tabs) before starting search.
