### ISSUE TITLE
Editor word wrap does not seem to work properly

### ISSUE THREAD

**Issue by dvdvideo1234** [pkulchenko/ZeroBraneStudio#1056] opened 2020-05-15 08:30 UTC
IDE info:
```
ZeroBrane Studio (1.70; MobDebug 0.702)
Copyright © 2011-2017 ZeroBrane LLC
Paul Kulchenko
Licensed under the MIT License. 
Based on Estrela Editor
Copyright © 2008-2011 Luxinia DevTeam
Christoph Kubisch, Eike Decker
Licensed under the MIT License. 

Based on wxLua editor
Copyright © 2002-2005 Lomtick Software
J. Winwood, John Labenski
Licensed under wxWindows Library License, v3. 
Built with wxWidgets 3.1.1, wxLua 2.8.12.3 
```
User configurations
```lua
--[[--
  Use this file to specify **User** preferences.
  Review [examples](+D:\LuaIDE\cfg\user-sample.lua) or check [online documentation](http://studio.zerobrane.com/documentation.html) for details.
--]]--

print(package.path)

editor.foldtype = 'box'
editor.smartindent = true
editor.tabwidth = 2
editor.usetabs = false
editor.usewrap = false -- Disable long lines wrapping to the next line
```
![image](https://user-images.githubusercontent.com/9112662/82029257-6bc10600-969f-11ea-8b70-a7c911f73658.png)

**Comment by pkulchenko** [comment] 2020-05-15 17:22
@dvdvideo1234, not sure what to tell you. I haven't seen any issues with the wrapping even in the previous versions, but would be great if you could test on 1.90 (instead of 1.70 you are using, as that version is pretty old). Also, how long is that line and what OS are you on? If you can reproduce it on 1.90, I'll check what's going on, but so far I haven't been able to reproduce even on very long lines (x00000 columns wide).

**Comment by dvdvideo1234** [comment] 2020-05-15 19:58
@pkulchenko On it. I will install 1.90. I am on Win7

**Comment by dvdvideo1234** [comment] 2020-05-27 15:00
@pkulchenko 

Hello I tested version 1.9 an this is the result:
```
ZeroBrane Studio (1.90; MobDebug 0.706)
Copyright © 2011-2020 ZeroBrane LLC
Paul Kulchenko
Licensed under the MIT License. 
Built with wxWidgets 3.1.4, wxLua 3.0.0.8, Scintilla 3.7.2 
Based on Estrela Editor
Copyright © 2008-2011 Luxinia DevTeam
Christoph Kubisch, Eike Decker
Licensed under the MIT License. 

Based on wxLua editor
Copyright © 2002-2005 Lomtick Software
J. Winwood, John Labenski
Licensed under wxWindows Library License, v3. 
```
![image](https://user-images.githubusercontent.com/9112662/83036979-e6950400-a043-11ea-94d0-e02239aefcdb.png)

**Comment by pkulchenko** [comment] 2020-05-27 15:21
@dvdvideo1234, how long are these lines? Are any lines being wrapped?

Can you run `ide:GetEditor():GetWrapMode()` in the console when `test.lua` is the active editor and copy the result here?

Also, can you take a full screenshot of the wrapped editor (including the right and bottom borders)?

**Comment by dvdvideo1234** [comment] 2020-05-27 18:05
@pkulchenko 

![image](https://user-images.githubusercontent.com/9112662/83056258-c2462100-a05d-11ea-8c7a-9c33933c3284.png)

**Comment by pkulchenko** [comment] 2020-05-27 19:46
@dvdvideo1234, given the response, it looks like the wrapping is not enabled for this editor window. Not sure why, but I'd like to check on two things. What is the value of `ide.config.editor.usewrap` and `ide.config.editor.wrapmode` (you can type this into Local Console) and what happens after you execute `ide:GetEditor():SetWrapMode(1)` in the console? Does it switch to non-wrap mode?

Also, can you try the following patch to see if this fixes the issue:

```diff
diff --git a/src/editor/editor.lua b/src/editor/editor.lua
index 060db817..399702a3 100644
--- a/src/editor/editor.lua
+++ b/src/editor/editor.lua
@@ -747,6 +747,7 @@ function CreateEditor(bare)
       end
     end
   else
+    editor:SetWrapMode(wxstc.wxSTC_WRAP_NONE)
     editor:SetScrollWidth(100) -- set default width
     editor:SetScrollWidthTracking(1) -- enable width auto-adjustment
   end
```

This patch explicitly sets the value (but it should be set by default anyway).

**Comment by dvdvideo1234** [comment] 2020-05-28 16:44
@pkulchenko 
Hello,

```
ide.config.editor.usewrap
true
ide.config.editor.wrapmode
1
ide:GetEditor():SetWrapMode(1)

```

The request `ide:GetEditor():SetWrapMode(1)` does not change wrapping. It stays the way it is.

**Comment by pkulchenko** [comment] 2020-05-28 16:53
> In the console I notices that print(package.path) was erroring... Wonder why. Removed it and now it works.

That was my guess that the config was not executing fully; you should see an error message to that effect in the console. Closing...

**Closed by pkulchenko** 2020-05-28 16:53 UTC
