### ISSUE TITLE
luacheck options in project configuration is not used

### ISSUE THREAD

**Issue by imolein** [pkulchenko/ZeroBraneStudio#1013] opened 2019-09-25 09:38 UTC
I want to use luacheck in a project and set up a project configuration file using your [projectsettings.lua](https://github.com/pkulchenko/ZeroBranePackage/blob/master/projectsettings.lua), where I configured the options for luacheck as explained in the documentation:
```
staticanalyzer.luacheck = {
  options = {
    read_globals = { 'ok', 'eq', 'eqok', 'spy' }
  }
}
```
When I check the value of `ide.config.staticanalyzer.luacheck` using the local console in ZB, it shows me the table with the correct settings, but these settings are not applied and it seems like luacheck isn't even activated and used. I also tried it with the example from the documentation with the same result.

If I configure the same in my user configuration, it works without a problem.

**Comment by pkulchenko** [comment] 2019-09-25 16:06
@imolein, thank you for the report. Should be fixed in the master branch.

**Closed** 2019-09-25 16:05 UTC

**Comment by imolein** [comment] 2019-09-25 18:08
Thanks a lot, it is working now.

The  only thing which I noticed is, that luacheck is not detecting wrongly declared globals with the standard configuration. In version 1.80 this was the case if I remember correctly. If I set 
```lua
options = { std = 'max' }
```
which is the default in standalone luacheck, it is working.

**Comment by pkulchenko** [comment] 2019-09-25 18:20
It appears to be by design, given that the default configuration is to ignore globals:

```
      ignore = config.ignore or {
        "11.", -- setting, accessing and mutating globals
        "6..", -- whitespace and style warnings
      },
```

Are you suggesting to remove "11." from the default?

**Comment by imolein** [comment] 2019-09-25 18:43
Ah dammit, I missed that when I was looking at `inspect.lua`...

Yes I would recommand to remove **11.** from `ignore`, since
* it's the standard for standalone luacheck
* it's good to know if you set, access or mutating globals by accident
* LuaInspect warns you by default
* I currently don't see any reason why it should be ignored

Or if there is a reason for this, which I don't aware of, there should be added a note about the per default ignored warnings to the docs.

**Comment by pkulchenko** [comment] 2019-09-25 22:05
@imolein, I agree; I pushed the change that enables that.
