### ISSUE TITLE
App freezes when clicking in autocomplete listview on OSX

### ISSUE THREAD

**Issue by toturi** [pkulchenko/ZeroBraneStudio#496] opened 2015-07-08 19:52 UTC
Summary: 
The ZeroBrane editor will freeze if the user clicks on the autocomplete list view's scroll bar. This occurs on OSX using the code from GitHub that I pulled at July 8, 12:30PM PST. I have tried on Windows with ZeroBrane 1.10, but have not been able to reproduce.

System:
OSX 10.10.4

Steps to Reproduce:
1) Launch ZeroBrane Studio.
2) Under Project -> Lua Interpreter, select Lua (any will do, but I was able to repro with Lua and Corona).
3) Open a project in a clean directory.
4) Create a new file or open an existing one.
5) In the editor, type a namespace that will cause the autocomplete list view to appear (I was able to repro with "math." and "display." if using Corona interpreter).
6) Once the autocomplete list view appears, use the mouse to click in the scroll bar of the list view.
7) Observe that the application is no longer responsive and the user must force quit.

Additional Notes:
The freeze seems to only occur if the mouse click happens in the scroll bar. You can use the arrow keys to cycle through the list view, or use the mouse wheel to scroll the list view without any problems. Pressing Return with an item highlighted in the list view will "choose" it and it will be inserted into the editor. However, mouse clicking does not choose any item in the list view, although it does not cause the crash either.

**Comment by pkulchenko** [comment] 2015-07-08 20:15
@toturi, thank you for the report; I'll check shortly what may be going on.

Just to confirm, the issue does *not* happen with ZeroBrane 1.10 for you, right?

**Comment by toturi** [comment] 2015-07-08 20:22
@pkulchenko Hi, sorry, I included info about 1.10 because that's the version I'm using on Windows. The problem does not occur on Windows. However, I just tried in 1.10 on OS X and I can confirm that the issue occurs in 1.10 as well. I primarily use the development version so I didn't initially try on 1.10 on OS X.

**Comment by pkulchenko** [comment] 2015-07-08 20:23
no problem; so the issue is with mouse clicks in that popup windows... I'll take a look.

**Comment by pkulchenko** [comment] 2015-07-09 01:08
@toturi, give it a try; should be fixed now.

**Closed** 2015-07-09 01:08 UTC
Labels: Bug

**Comment by toturi** [comment] 2015-07-09 01:18
@pkulchenko Just pulled and tried it out. Works great, no more freeze. Thanks again for such great support!

**Comment by pkulchenko** [comment] 2015-07-09 02:20
Sounds good; thanks for the update.
