### ISSUE TITLE
No call stack when debugging Lua scripts in GENie

### ISSUE THREAD

**Issue by stuartcarnie** [pkulchenko/ZeroBraneStudio#641] opened 2016-05-12 23:10 UTC
When debugging Lua scripts in [GENie](https://github.com/bkaradzic/GENie), I typically see an error similar to the following:

![screen shot 2016-05-12 at 4 08 10 pm](https://cloud.githubusercontent.com/assets/52852/15233198/c0df9a28-185b-11e6-9f9b-53efcfed6011.png)

**Comment by pkulchenko** [comment] 2016-05-13 00:48
@stuartcarnie, thank you for the report. I suspect it may have something to do with the (de)serialization of the stack frames (or the variables in them). Could you apply the following diff (with the appropriate path modification) to capture the snapshot of the stack that fails to deserialize?

```lua
diff --git a/lualibs/mobdebug/mobdebug.lua b/lualibs/mobdebug/mobdebug.lua
index 8c81325..2c63130 100644
--- a/lualibs/mobdebug/mobdebug.lua
+++ b/lualibs/mobdebug/mobdebug.lua
@@ -1450,6 +1450,11 @@ local function handle(params, client, options)
     local _, _, status, res = string.find(resp, "^(%d+)%s+%w+%s+(.+)%s*$")
     if status == "200" then
       local func, err = loadstring(res)
+local f = io.open('d:/zbs.log', 'a')
+if f then
+  f:write((err and err.."\n" or "").."\n"..res)
+  f:close()
+end
       if func == nil then
         print("Error in stack information: " .. err)
         return nil, nil, err
```

You can email me the snapshot directly...

**Comment by stuartcarnie** [comment] 2016-05-13 01:47
Should be waiting in your inbox

**Comment by stuartcarnie** [comment] 2016-05-13 02:34
`_[1][3]._ENV[1]._profiler.prevented_functions[_profiler_hook_wrapper_by_time]=2;` causes the error because `_profiler_hook_wrapper_by_time` doesn't exist

**Comment by pkulchenko** [comment] 2016-05-13 05:16
@stuartcarnie, yes, I think you are right about the problem. Now the challenge is to reproduce the data structure that produces the incorrect output so that I can debug it. Clearly that reference is missing its prefix, but I have no idea yet why.

Looking at the similar function `_profiler_hook_wrapper_by_call`, the prefix probably should be `_[1][3]._ENV[1].`. I tried adding it and serializing the data structure again, but it didn't produce any error. This approach may take several tries, but worked well in the past.

I tried with both Lua5.1 and Lua5.3, but so far has not been able to make it fail in serializing this structure. If nothing works, I may end up setting up GENie to try debugging it right when it happens.

**Comment by stuartcarnie** [comment] 2016-05-13 05:21
I saw that too - how would I debug mobdebug, as I can try too

**Comment by pkulchenko** [comment] 2016-05-13 05:36
I wish I had a good answer. The logic is actually in serpent, which is included in mobdebug. I suspect the problem can be seen on line 213 where the `path` is being calculated (which is like a prefix for the current value). You may try to put an `if` statement for the key that matches the key that is not correctly serialized to print and explore the values. I suspect it will be quite difficult to debug given the sheer size of the data structure we are dealing with. Just one quite note on the variables there: `out` keeps track of the "normal" output for the serialized data structure and `sref` (from self-reference) keeps track of those data structures that require assignments after the main table is built (because of self- or multi-refs).

Since the problem happens quite frequently for you, do you see it always happening with the same function or are there different functions in play?

**Comment by stuartcarnie** [comment] 2016-05-13 05:51
I presume `var2str` has a big part in the serialization? It is interesting that a similar function in the same file (profiler.lua) serialized with the correct prefix

**Comment by stuartcarnie** [comment] 2016-05-13 05:52
It does happen every time however there are times where I can step a number of lines before it breaks

**Comment by pkulchenko** [comment] 2016-05-13 05:54
Knowing the last step it breaks on usually helps as it likely changes the data in the way that "breaks" them.

yes, `var2str` is one of the key parts and is called recursively with slightly different parameters.

**Comment by stuartcarnie** [comment] 2016-05-13 09:00
Found part of the issue. GENie replaces the `type` function, [per this code](https://github.com/bkaradzic/GENie/blob/master/src/base/globals.lua#L170-L179). The majority of the time, I'm seeing `table: 0xfaceface` rendered in the output (no quotes), because `type` does not return `table`.

**Comment by stuartcarnie** [comment] 2016-05-13 15:36
@pkulchenko I renamed `type` to `typex` and all is well…

**Comment by pkulchenko** [comment] 2016-05-13 15:47
Stuart, good; thank you for the update.

I wonder what can be done in the serializer to avoid this issue. I can try to localize `type`, but it may be too late if `type` is modified before the debugger and serializer are loaded.

I now see why I couldn't reproduce it in my tests, even if the structure was correct; I was missing all the metatables assigned, plus whatever modifications GENie did to the core functions.

**Comment by stuartcarnie** [comment] 2016-05-13 15:49
Fortunately, it seems like `type` was the only core function modified. It was easy enough to change in GENie. I think the best you could do is fix `safestr` so that it is explicit with the types, rather than the `~= "string"` test.

**Comment by stuartcarnie** [comment] 2016-05-13 15:56
@pkulchenko, @bkaradzic is ok with me changing it to `typex`, so that will solve our issue too

**Comment by pkulchenko** [comment] 2016-05-13 15:56
ok; that's cool. I think it's bad idea to change `type` this way; there is now no way to properly check the type.

Just for completeness, can you try the following patch to the serializer (and restore `type` modification):

```diff
diff --git a/lualibs/mobdebug/mobdebug.lua b/lualibs/mobdebug/mobdebug.lua
index 8c81325..030f649 100644
--- a/lualibs/mobdebug/mobdebug.lua
+++ b/lualibs/mobdebug/mobdebug.lua
@@ -185,7 +185,7 @@ local function s(t, opts)
       seen[t] = insref or spath
       if mt.__serialize then t = mt.__serialize(t) else t = tostring(t) end
       ttype = type(t) end -- new value falls through to be serialized
-    if ttype == "table" then
+    if ttype == "table" or mt then
       if level >= maxl then return tag..'{}'..comment('max', level) end
       seen[t] = insref or spath
       if next(t) == nil then return tag..'{}'..comment(t, level) end -- table empty
```

**Comment by pkulchenko** [comment] 2016-05-14 23:12
@stuartcarnie, scratch that earlier comment; this change I suggested won't work.

Since you fixed it in GENie, closing this.

**Closed by pkulchenko** 2016-05-14 23:12 UTC
Labels: Bug

**Comment by pkulchenko** [comment] 2018-03-11 23:37
@stuartcarnie, @bkaradzic, how does the debugging work with GENie if it links Lua interpreter statically, doesn't export any (Lua) symbols, and doesn't include luasocket? How do it able to load luasocket library without running into multi-VM issue?
