### ISSUE TITLE
Feature request : Version Control

### ISSUE THREAD

**Issue by Antix-Development** [pkulchenko/ZeroBraneStudio#1083] opened 2020-10-19 20:09 UTC
Will ZBS ever have baked in version control via git? That would be pretty cool :)

**Comment by pkulchenko** [comment] 2020-10-20 04:46
I don't have a plan to work on version control support soon, but I linked an experimental extension for SVN integration in #165. I'm closing this as a duplicate of that old ticket, but feel free to continue the discussion there.

**Closed by pkulchenko** 2020-10-20 04:46 UTC
