### ISSUE TITLE
Folding in Perl files doesn't respect `foldcompact` setting.

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBraneStudio#847] opened 2017-12-24 13:06 UTC
1. Is it possible set some settings for specific lexer.
E.g. in `user.lua` I set `editor.foldcompact = false` but it does not work for
perl files where it still fold empy lines

2. Is it possible add menu item for popup menu from external package.
I wrope package and it works. (I bind it to hotkey combination). But now
I want add it to popup menu in editor. I did this for now by copy code in 
editor.lua file.

**Comment by pkulchenko** [comment] 2017-12-24 20:26
> Is it possible set some settings for specific lexer. E.g. in user.lua I set editor.foldcompact = false but it does not work for perl files where it still fold empy lines

No, it's not possible to do it for a particular lexer, but you can do it per editor, so you can have onEditorLoad event and check the lexer in the editor and reconfigure it as needed.

If it doesn't work for Perl files, it may be bug in its handling in the lexer. Do you have a specific example it doesn't work on for me to check? Also do you use v1.70 of the IDE?

> Is it possible add menu item for popup menu from external package. I wrope package and it works. (I bind it to hotkey combination). But now  I want add it to popup menu in editor. I did this for now by copy code in editor.lua file.

Yes, you can definitely do this. Check `onMenuEditor` event and the example in `packages/sample.lua` file. You can also search existing packages for this callback, as there are several that use it to add a menu item.

In general, there is rarely a need to edit anything in the core package, so if you run into a situation like this, let me know and I'll either point you to the existing API that does this or consider extending the API to handle it. It may also be better to [ping me in IRC or use the maillist](https://studio.zerobrane.com/community) for questions.

**Comment by pkulchenko** [comment] 2017-12-25 01:04
I just tested on the following simple perl script, and the fold is showing for lines 1-3, which is what you'd expect with `editor.foldcompact = false`.

```pl
if (1) {
  print(1)
}
  
print(2)
```

I'm using lexlpeg-based lexer for pl files, which is enabled by default (in 1.60 on Windows/macOS and in 1.70 on Linux).

**Comment by pkulchenko** [comment] 2017-12-25 01:08
I take that back on `foldcompact`; there were some whitespace characters, which made it look like the result was correct. I don't see why it would be wrong for the perl files, but will take a look at the lexer.

**Comment by moteus** [comment] 2017-12-25 08:28
Thanks. onMenuEditor works.
I do not know how I did not find this onMenuEditor example.
I really try look at :)

**Comment by pkulchenko** [comment] 2017-12-25 17:14
I checked the compact folding and it looks like a limitation of the Scintillua, which is used as a lexer for all non-lua formats. I've sent a message to its author and will update the ticket when I get more information on it. Closing for now.

**Closed by pkulchenko** 2017-12-25 17:14 UTC
Labels: Documentation

**Comment by moteus** [comment] 2018-01-12 10:46
ZeroBrane seems uses lpeg version for Perl. `editor.spec.lexer=="lexlpeg.perl"`.
How to try original Scintilla lexer ?

**Comment by pkulchenko** [comment] 2018-01-13 05:58
It's not a problem to set a different lexer; for example, you can set the value to `wxstc.wxSTC_LEX_PERL`. The problem is that the constants that control the styling are completely different for each lexer, so, for example, `wxSTC_PL_NUMBER` is completely different from `wxSTC_LUA_NUMBER`, so someone has to map both of them to the same style to make it look similar for Perl and Lua files.

Using lexlpeg lexers sidesteps this problem (although there are drawbacks as well) by mapping different styles to their names, instead of numerical constants, which are then mapped to styles.

You can still use a embeded Perl lexer, but you need to re-map its styles to the spec names that the IDE recognizes. For example, you can try the following plugin:

```lua
-- Copyright 2014 Paul Kulchenko, ZeroBrane LLC; All rights reserved

local spec = {
  exts = {"pl"},
  lexer = wxstc.wxSTC_LEX_PERL,
  apitype = "perl",

  lexerstyleconvert = {
    text = {wxstc.wxSTC_PL_DEFAULT,},
    comment = {wxstc.wxSTC_PL_COMMENT,},
    stringeol = {wxstc.wxSTC_PL_STRINGEOL,},
    number = {wxstc.wxSTC_PL_NUMBER,},
    stringtxt = {
      wxstc.wxSTC_PL_STRING,
      wxstc.wxSTC_PL_STRING_Q,
    },
    lexerdef= {
    },
    keywords0 = {wxstc.wxSTC_PL_WORD,},
    preprocessor= {wxstc.wxSTC_PL_PREPROCESSOR,},
  },

  keywords = {
    "if for"
  },
}

return {
  name = "Perl syntax highlighting",
  description = "Adds Perl syntax highlighting.",
  author = "Paul Kulchenko",
  version = 0.1,

  onRegister = function(self) ide:AddSpec("perl", spec) end,
  onUnRegister = function(self) ide:RemoveSpec("perl") end,
}
```

Here is the full list of Perl constants (most of them are self-explanatory); you'll need to map some of them by adding them to `lexerstyleconvert` table:

```C
#define wxSTC_PL_DEFAULT
#define wxSTC_PL_ERROR
#define wxSTC_PL_COMMENTLINE
#define wxSTC_PL_POD
#define wxSTC_PL_NUMBER
#define wxSTC_PL_WORD
#define wxSTC_PL_STRING
#define wxSTC_PL_CHARACTER
#define wxSTC_PL_PUNCTUATION
#define wxSTC_PL_PREPROCESSOR
#define wxSTC_PL_OPERATOR
#define wxSTC_PL_IDENTIFIER
#define wxSTC_PL_SCALAR
#define wxSTC_PL_ARRAY
#define wxSTC_PL_HASH
#define wxSTC_PL_SYMBOLTABLE
#define wxSTC_PL_VARIABLE_INDEXER
#define wxSTC_PL_REGEX
#define wxSTC_PL_REGSUBST
#define wxSTC_PL_LONGQUOTE
#define wxSTC_PL_BACKTICKS
#define wxSTC_PL_DATASECTION
#define wxSTC_PL_HERE_DELIM
#define wxSTC_PL_HERE_Q
#define wxSTC_PL_HERE_QQ
#define wxSTC_PL_HERE_QX
#define wxSTC_PL_STRING_Q
#define wxSTC_PL_STRING_QQ
#define wxSTC_PL_STRING_QX
#define wxSTC_PL_STRING_QR
#define wxSTC_PL_STRING_QW
#define wxSTC_PL_POD_VERB
#define wxSTC_PL_SUB_PROTOTYPE
#define wxSTC_PL_FORMAT_IDENT
#define wxSTC_PL_FORMAT
#define wxSTC_PL_STRING_VAR
#define wxSTC_PL_XLAT
#define wxSTC_PL_REGEX_VAR
#define wxSTC_PL_REGSUBST_VAR
#define wxSTC_PL_BACKTICKS_VAR
#define wxSTC_PL_HERE_QQ_VAR
#define wxSTC_PL_HERE_QX_VAR
#define wxSTC_PL_STRING_QQ_VAR
#define wxSTC_PL_STRING_QX_VAR
#define wxSTC_PL_STRING_QR_VAR
```

**Comment by moteus** [comment] 2018-01-13 13:17
Thanks for response. I tried this one and found that it not possinle use more than one keywords list
But i make simple fix in lexer and it seems fix my problem.
Just need do not set `FOLD_BLANK` [flag here](https://github.com/pkulchenko/ZeroBraneStudio/blob/master/lualibs/lexers/lexer.lua#L1228)
Do not figure out how pass settings from ZBS to lexer though, so just remove this flag.

Also found problem with comments started with `#` char. ZBS hides this character (i know why just need way to turn this off in this case)
