### ISSUE TITLE
Error loading module 'wx' 

### ISSUE THREAD

**Issue by ssakhavi** [pkulchenko/ZeroBraneStudio#417] opened 2015-03-03 10:28 UTC
Hi, I get the following error:
```
bin/linux/x64/lua: error loading module 'wx' from file 'bin/libwx.dylib':
	bin/libwx.dylib: invalid ELF header
stack traceback:
	[C]: at 0x004820e4
	[C]: in function 'require'
	src/main.lua:30: in main chunk
	[C]: at 0x004054e8
```
I am using **Ubuntu 14.04** and my lua version is **5.3**
I've seen your responses to this problem but unfortunately, none of them have worked for me.

**Comment by pkulchenko** [comment] 2015-03-03 17:26
@ssakhavi, do you see this issue when you try to start ZBS or when you run an application from the IDE?

It seems you are running from the cloned repository and for some reason the application is trying to load wx library from `bin/libwx.dylib`, which is an OSX library, not Linux. Can you describe in a bit more detail your setup?

**Comment by ssakhavi** [comment] 2015-03-03 23:07
Yes.

I have used different methods for installation.
I get the same error for all.

Currently, I have cloned the repo and ran `zbstudio.sh`. This is where I get the error.

I have also downloaded the newest version from the site and installed. The application doesn't run.

**Comment by pkulchenko** [comment] 2015-03-03 23:25
Ok, can you open `src/main.lua` and add the following line to it around line 30 (before `require "wx"`):

```lua
print(islinux, iswindows, os.getenv('DYLD_LIBRARY_PATH'), io.open("/proc"), package.cpath) os.exit()
```

Then start the application as before (`./zbstudio.sh`). You should only see one line printed. Please post the content of that line. Thank you.

**Comment by ssakhavi** [comment] 2015-03-04 01:53
```false	nil	
/home/siavash/torch-distro/install/lib:/home/siavash/torch-distro/install/lib:/home/siavash/torch-distro/install/lib:	file (0x024f8010)	bin/lib?.dylib;bin/clibs/?.dylib;./?.so;/usr/local/lib/lua/5.1/?.so;/usr/local/lib/lua/5.1/loadall.so```

**Comment by ssakhavi** [comment] 2015-03-04 02:03
I should mention that whenever I run the `zbstudio.sh` it gets stuck afterwords and I have to force exit.

**Comment by pkulchenko** [comment] 2015-03-04 02:25
This is caused by the check for `DYLD_LIBRARY_PATH`, which I expected to be set only on OSX, but in your case it's set on Linux, so it gets misdetected.

If you replace `local islinux = not iswindows and not os.getenv('DYLD_LIBRARY_PATH') and io.open("/proc")` with `local islinux = not iswindows and io.open("/proc")`, I'd expect it to work.

**Comment by ssakhavi** [comment] 2015-03-04 03:29
Excellent!  It worked!

Thanks @pkulchenko !

**Comment by pkulchenko** [comment] 2015-03-04 03:31
ok; I'll get it checked in shortly. Thank you for the confirmation.

**Closed** 2015-03-04 05:58 UTC
Labels: Bug
