### ISSUE TITLE
Error when toggle window

### ISSUE THREAD

**Issue by moteus** [pkulchenko/ZeroBraneStudio#845] opened 2017-12-21 09:57 UTC
Ubuntu 16.04 x64

I got this when choose Menu->View->Output Window
Same with markers Window

```
wxLua Runtime Error:
Lua: Error while running chunk
src/editor/menu_view.lua:68: attempt to index field 'window' (a nil value)
stack traceback:
	src/editor/menu_view.lua:68: in function <src/editor/menu_view.lua:64>
	[C]: at 0x7f826835d1bd
	src/main.lua:854: in main chunk
	[C]: at 0x00404f08
```

PS. Output window already shown.

**Comment by pkulchenko** [comment] 2017-12-21 16:32
I can't reproduce this issue. Were there some actions before this happened?

**Comment by pkulchenko** [comment] 2017-12-21 16:38
It looks like the window component itself got destroyed, which shouldn't normally happen. Does this happen without any plugins or custom code?

**Comment by moteus** [comment] 2017-12-27 07:57
I think it is not related to my changes. I just add path mapping and change folding clicks.
Also now I also can not reproduce it either.
Also I note that Items related with debug (Step in, Step out etc) do not turn on as enabled when
I start debug. But key shortcuts works as expected.
Then some toggle menu item shows its state in inverted mode. E.g. now I have my stack window shown but menu item does not checked. When I check menu  window removes.

**Comment by pkulchenko** [comment] 2017-12-27 18:57
There has been a similar report on Win10 and Debian, but I could never reproduce this and none else has reported this. See this thread for the discussion and couple of things to try that I suggested: https://www.freelists.org/post/zerobrane/save-icon-remains-disabled,3

> Also now I also can not reproduce it either.

This may be related to the issue of UI not being updated properly, as it would allow the menu item to be in the wrong state and to trigger the wrong processing.

Closing for now, but if you can reproduce the issue, feel free to update and reopen the ticket.

**Closed by pkulchenko** 2017-12-27 18:57 UTC
Labels: Bug, Can't reproduce
