### ISSUE TITLE
Runtime Error during auto-complete when `strategy` is set to 1

### ISSUE THREAD

**Issue by CetoBasilius** [pkulchenko/ZeroBraneStudio#660] opened 2016-06-20 15:33 UTC
When trying to autocomplete a Corona SDK line, zerobrane alerts me with a runtime error. The error happens in 1.30 and in latest commit, 2e64af4. Using Mac OSX 10.11.4 (15E65). This happens only when i have the following in my user settings:

    acandtip.strategy = 1
    autocomplete = true

The error does not happen with an empty user.lua. The title says "wxLua Runtime Error". trace is the following on 2e64af4:

    Lua: Error while running chunk
    src/editor/autocomplete.lua:633: attempt to call method 'sub' (a nil value)
    stack traceback:
	src/editor/autocomplete.lua:633: in function <src/editor/autocomplete.lua:632>
	[C]: in function 'sort'
	src/editor/autocomplete.lua:632: in function 'CreateAutoCompList'
	src/editor/editor.lua:242: in function 'EditorAutoComplete'
	src/editor/editor.lua:1010: in function <src/editor/editor.lua:1010>
	src/editor/editor.lua:1212: in function <src/editor/editor.lua:1211>
	[C]: at 0x01051beb
	src/main.lua:888: in main chunk
	[C]: at 0x00001c80

I was going to type `logGroup:insert()` but it showed up when autocompleting the "insert" part. This is the function i was coding:

    function logger.showLog()
	if logGroup then
		logGroup = display.newGroup()
	end
	
	logText = display.newText({
		x = display.contentCenterX,
		y = display.screenOriginY,
		width = display.viewableContentWidth,
		height = display.viewableContentHeight * 0.25,
	})
	
	logGroup:
    end

I'm using a full user.lua on the screenshot, but i've tested with only those 2 flags and I can reproduce it no problem, have not tested with a small snippet:
<img width="649" alt="screen shot 2016-06-20 at 10 28 03 am" src="https://cloud.githubusercontent.com/assets/4663385/16200145/b21e829e-36d1-11e6-8733-50d66f1071c7.png">

It appears an item inside the table is not a string, but another table, which means it does not have the sub function

**Comment by pkulchenko** [comment] 2016-06-20 16:15
@CetoBasilius, thank you for the report. There is indeed an issue with `acandtip.strategy=1` setting, so the workaround is to use the default `acandtip.startegy=2` value.

I think you've identified the cause of this correctly (the cache is expected to be a string, but is a table instead) and I'll check how this issue can be fixed. Curious, do you expect the results for `strategy=1` to be better than for `strategy=2`?

**Comment by CetoBasilius** [comment] 2016-06-20 17:41
I've already changed the strategy back to 2, i was just testing it hehe

**Comment by pkulchenko** [comment] 2016-06-21 19:49
@CetoBasilius, should be fixed now for both `strategy=1` and `strategy=0`.

**Closed** 2016-06-21 19:48 UTC
Labels: Bug
