### ISSUE TITLE
norwegian keyboard layout issues with the ~ character

### ISSUE THREAD

**Issue by CapsAdmin** [pkulchenko/ZeroBraneStudio#478] opened 2015-06-03 08:05 UTC
Typing ~ requires me to hold alt gr and press the top button left of enter twice for it to appear. This seems to be very difficult to do in zerobrane as it rarely appears.

**Comment by pkulchenko** [comment] 2015-06-03 21:59
This seems to be a duplicate of #113 and #232; the first ticket provides a workaround. Please re-open if I misunderstood the issue.

**Closed by pkulchenko** 2015-06-03 21:59 UTC
