### ISSUE TITLE
Use uchardet and iconv for files with non utf-8 encodings

### ISSUE THREAD

**Issue by zohooo** [pkulchenko/ZeroBraneStudio#543] opened 2015-10-14 03:05 UTC
I have searched the issues and found several issues related to non utf8 encodings. It seems that with unicode build of wxWidgets, It is difficult to make wxStyledTextCtrl use non utf8 encodings, although Scintilla supports many encodings.

But what about making the encoding detecting and converting them to utf-8 before passing file content to wxstc?  We colud use [uchardet](https://github.com/BYVoid/uchardet) and [lua-iconv](https://github.com/ittner/lua-iconv) for these tasks.

**Comment by pkulchenko** [comment] 2015-10-14 03:24
@zohoo, it's possible to make it work properly even with the Unicode build, but the version of wxlua we are using is missing couple of calls. See this discussion for some details and the solution: http://sourceforge.net/p/wxlua/mailman/message/32184840/

These calls have been added to wxlua, but I haven't upgraded yet to more recent version of wxwidgets as I'm waiting for a couple of fixes. See #260 ticket for details.

The method that is described in the discussion thread (using `*TextRaw` methods) has the advantage of properly retrieving and saving invalid UTF8 characters, which would make some of the workarounds currently in place unnecessary. There may still be things I'm not taking into consideration right now, but I plan to test the upgrade, which should expose those.

Since this is a duplicate of several tickets mentioned in [this comment](260#issuecomment-41988062), I'm closing it, but we can continue this discussion either here or in one of the related tickets.

If you want, you can compile the updated version of the IDE (using the current version of wxwidgets/wxlua) and switch to using "raw" methods to see if this resolves the issue. I've done some preliminary testing to confirm that, but not any extensive testing.

**Closed by pkulchenko** 2015-10-14 03:24 UTC

**Comment by zohooo** [comment] 2015-10-14 04:31
Those "invalid UTF-8 files" is in fact valid files with other encodings. If we could detecting their encodings and convert them to utf8 encoding before insert their content to the editor, then we don't need those `*TextRaw` methods anymore.

If we treat those files as UTF-8 files and replace non-ascii characters with `SYN`, then we could lost these characters after modifying and saving them again. Losting data is bad, so I think current approach is not good enough.

I think encoding detecting is a good feature for text editors.

**Comment by pkulchenko** [comment] 2015-10-14 04:56
I agree with that, and using `*TextRaw` methods no `SYN` replacement will be needed. I agree, the files won't be handled correctly as UTF-8, but all the characters will be displayed (and saved back) as-is without any replacement. This is already handled by Scintilla; it's just the integration between wxwidgets and Scintilla requires those "special" calls.

It's still possible to use other encodings with Scintilla, but I don't think it's going to be needed. You can try yourself with `editor:SetCodePage()`, but the problem is that it's unlikely to be handled correctly by wxwidgets as it still expects valid UTF8 outside of few calls mentioned in discussion I linked.

**Comment by zohooo** [comment] 2015-10-14 12:38
For non utf-8 files, even if all the characters will be displayed by using `*TextRaw` method, users still could not read these non-ascii characters in ZBS. In general these characters appear in code comments. It is not a good experience for users to edit a source file with lots of none readable comments...

**Comment by pkulchenko** [comment] 2015-10-30 17:25
Here is another idea (based on IRC discussion with `eomer`): have a set of filters that do direct conversion to/from UTF8 (along the lines suggested [here](http://stackoverflow.com/questions/16624036/how-to-convert-windows-1256-to-utf-8-in-lua/16627763#16627763), using a [table like this](http://www.unicode.org/Public/MAPPINGS/VENDORS/MICSFT/WINDOWS/CP1252.TXT)) and have "Open with encoding" and "Save with encoding" menu that have sub-menus based on registered encodings. If only `CP1252` is registered, then it's the only encoding you can see in the sub-menus.

It's not as elaborate as auto-detection of the encoding, but it's significantly less work, can be provided as a plugin and can be easily extended with more encoding as needed.

**Comment by zohooo** [comment] 2015-10-31 07:26
In fact, I'm writing a [LaTeX editor](https://github.com/zohooo/quadtext) which is based on wxLua editor and inspired by ZeroBrane Studio. Therefore I also have to handle this encoding problem.

In my opinion, `iconv` would be more faster than doing encoding conversion by lua. Besides your idea, I think it would be good to also add a **default encoding** setting for users.

As to encoding detection, It would be another enhencement after encoding conversion.

**Comment by pkulchenko** [comment] 2015-10-31 16:30
> In fact, I'm writing a LaTeX editor which is based on wxLua editor and inspired by ZeroBrane Studio. Therefore I also have to handle this encoding problem.

Interesting; I've been working on something similar using [SILE](https://github.com/simoncozens/sile).

> In my opinion, iconv would be more faster than doing encoding conversion by lua. Besides your idea, I think it would be good to also add a default encoding setting for users.

It would definitely be faster, but I'm not yet sure how much of a problem it's going to be as the conversion is going to only be triggered on saving/loading and on regular-sized text files it may not be an issue.

> As to encoding detection, It would be another enhencement after encoding conversion.

Yes, detection is a different problem; I looked at how uchardet does it and it's all based on probabilities and the converter with the largest confidence (based on frequency tables) wins. These days I'd expect most users to know charsets/codepages of the files they use. It would be nice to have this functionality, but it's probably a bit out of scope for the IDE.

**Comment by zohooo** [comment] 2015-11-11 04:51
In latest commits of my LaTeX editor, I have added lua-iconv library. Also I used system encodings and system languages in guessing file encodings.

**Comment by pkulchenko** [comment] 2015-11-11 05:24
@zohooo, I like the approach you took with [encodings](https://github.com/zohooo/quadtext/blob/master/source/editor/encoding.lua). Does it work with the wxwidgets version that ZBS is using or is it missing some conversion calls you need?

**Comment by zohooo** [comment] 2015-11-11 11:45
There are several classes for encoding conversion in wxWidgets, but they are unavailable in wxLlua (see [my post](http://sourceforge.net/p/wxlua/mailman/message/34544768/) in wxLua mailing list). Therefore I have to use `iconv` instead.
